opencontainers/runtime-tools

README.md
current generate.go support  the generation of more `specs` items than listed in README , and in MAKEFILE we have the install function , this PR  keep README consistent with generate.go and MAKEFILE
Signed-off-by: Wang Qilin <qilin.wang@huawei.com>
=> update README.md to keep consistent with generate.go and MAKEFILE

README.md
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
=> Some fix to README

get-stage3.sh
`${parameter/pattern/string}` [isn't in POSIX 2013][1], which leads to:
43: ./get-stage3.sh: Bad substitution
when folks run a strictly-POSIX shell.  Replace it with [command
substitution][2] invoking [echo][3] and [sed][4].
An alternative to #5.
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03
[3]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html
[4]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html
=> get-stage3.sh: Replace non-POSIX `${FILE/${DATE}/current}` with sed

cmd/runtimetest/main.go, cmd/runtimetest/rlimit_linux.go, generate.go
=> Fix go vet and go lint errors

Makefile, cmd/runtimetest/main.go
Users can use make test to check gofmt/govet/golint errors.
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>
=> Add make test for Makefile and use make test to fix problems.

generate.go
Cross-posted from mrunalp/ocitools#15.
Most of these are covered by the requirements that landed in
opencontainers/specs#164, and I don't think the additional mqueue
mount is worth the space between the spec requirements and the
ocitools-generated configs.  More details in the commit messages.
There was some [discussion in the 2016-01-20 meeting][1] about the
meaning of lists that didn't include default entries, but I think
we're all on the same page that unset values mean “give me the
defaults”.  So this should be mergable without waiting for that
discussion to reach consensus.
[1]: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2016/opencontainers.2016-01-20-18.02.log.html#l-43
=> generate: Drop devices and mounts

generate.go
=> Fixes to ocitools generate to make it work with runc again

test_runtime.sh
=> Pass uuid to runc start per spec to make runtime tests work again

.gitignore, Makefile, man/ocitools-generate.1.md, man/ocitools-validate.1.md, man/ocitools.1.md
Also fix up Makefile so that it will install ocitools and man pages.
=> Add man pages for ocitools

generate.go
=> Add support for using a base template

CONTRIBUTING.md
This project seems to have been operating under the assumption that
the usual `Signed-off-by` ↔ DCO mapping applied.  But it's nice to
make that explicit.  This commit copies the current DCO section from
runtime-spec, but puts it in `CONTRIBUTING.md` for [a more native GitHub
experience][1].
Looking through the history of the repo, the only non-merge commits
without sign-offs are by Mrunal:
* 5286bb06 (Update runtime validation section, 2016-01-19)
* b71f0452 (Update README.md, 2015-11-09)
* 2c0e9e20 (Update help for generate, 2015-11-05)
* 850abe9f (Update README.md, 2015-09-15)
* bb903899 (Initial commit, 2015-09-15)
who clearly doesn't have a problem signing for the rest of his work
and is unlikely to have stolen those contributions from somewhere else
;).
[1]: …
=> CONTRIBUTING: Document Signed-off-by and the DCO

generate.go, man/ocitools-generate.1.md
Since a937f7a4 (Add support for using a base template, 2016-04-13,
`--mount-cgroups` is not `no`, that will lead to additional cgroup
entries in the mount array (even if there was already a cgroup entry
in the mount array).  Instead of writing logic to find and clobber
existing cgroup entries, just make the default the no-op setting.
=> generate: Change --mount-cgroups default to 'no'

man/ocitools-generate.1.md
These were typos from 78e69bf5 (Add man pages for ocitools,
2016-04-09, #33).
=> man/ocitools-generate: Fix three-space indents for some shell commands

README.md, man/ocitools-generate.1.md
This makes it easier to get a project overview from the README, and
avoids the tedium of keeping parallel sets of detailed docs up to
date.
=> README: Punt detailed command description to the man pages

man/ocitools-generate.1.md
With `--uid` so far from `--gid`, it seems clear that alphabetical order
was the original goal.  Make some adjustments to bring the current
content back in line.
=> man/ocitools-generate: Alphabetize the OPTIONS section

man/ocitools-generate.1.md
There are so many of these, I think it's time to follow grep(1) and
friends and punt the individual details to the OPTIONS section.
I stared off trying to adjust the metavars (to use the [Python
nomenclature][1]) to match the OPTIONS section, but there are so many
;).  And useful metavars in the synopsis would make the synopsis even
more unwieldy than it already was.
[1]: https://docs.python.org/3/library/argparse.html#metavar
=> man/ocitools-generate: Use [OPTIONS] in the synopsis

man/ocitools-generate.1.md
Which landed in a937f7a4 (Add support for using a base template,
2016-04-13, #35) and [still needs docs][1].
This PR builds on #42 and #44, so they should land first.  I'm happy
to rebase this commit on top of master as those PRs land, or it can
land with the merges I currently have in the branch.
[1]: https://github.com/opencontainers/ocitools/pull/35#issuecomment-210191802
=> man/ocitools-generate: Document --template

man/ocitools-generate.1.md
=> Add mount label man page content

CONTRIBUTING.md, MAINTAINERS_GUIDE.md
Each project in the OCI should have similar contributing guidelines
and maintainer guidelines.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Update contributing guidelines and add maintainer guidelines

validate.go
Original post in https://github.com/opencontainers/ocitools/pull/55
@mrunalp  PTAL
=> verify os and arch, following golang doc

generate.go
The default template has this information already, but user-supplied
templates may not.  Before this commit:
$ ocitools generate --template <(echo '{}')
$ head -n2 config.json
{
"ociVersion": "",
And after this commit, the last line is:
"ociVersion": "0.6.0-dev",
Regardless of this commit, template authors can set whatever version
they like without getting clobbered:
$ ocitools generate --template <(echo '{"ociVersion": "xyz"}')
$ head -n2 config.json
{
"ociVersion": "xyz",
=> generate: Set ociVersion if it wasn't set in the template

generate.go
Before this commit:
$ ocitools generate --template <(echo '{}')
$ grep args config.json
"args": null,
With this commit:
$ grep args config.json
"args": [],
That's still not a particularly useful value for the process
arguments, but it complies with the specs [“array of strings”
typing][1] (opencontainers/runtime-spec#416) and is closer to a
the useful entry (a non-empty array).
[1]: https://github.com/opencontainers/runtime-spec/blob/dbce512cec0cd0774b236980ec18a4f6a91bc77e/config.md#process-configuration
=> generate: Set process.args to an empty array if it was nil

generate.go
=> --privileged should turn off defaults for SELinux, Apparmor and seccomp

man/ocitools-generate.1.md, man/ocitools-validate.1.md
Man page does not show correctly.
=> SELinux: Fixup man page

generate.go, man/ocitools-generate.1.md
Details in the commit messages.
=> generate: Assorted namespace cleanups (add --user, no clobber, ...)

man/ocitools-generate.1.md
“is stopped” echoes [the spec][1].  I'd be a bit happier if the spec
used “exits” instead of “is stopped” (to avoid confusion with
SIGSTOP), but this man page is not the place to be generating new
language.
Fixes #41.
[1]: https://github.com/opencontainers/runtime-spec/blob/v0.5.0/config.md#poststop
=> man/ocitools-generate: Reword --poststop (after container-process exit)

validate.go
fix https://github.com/opencontainers/ocitools/issues/67
=> verify: config is encoded in utf8; cwd is absolute path; env is valid

validate.go
These landed as CheckMounts in 647e3552 (bundle validate update to
0.3.0, 2016-02-23, #20), but both checks are too strict.
The first (destination exists in the rootfs) errors on valid cases
like:
"mounts": [
{
"source": "users",
"destination": "/home",
"type": "bind"
},
{
"source": "none",
"destination": "/home/wking",
"type": "tmpfs"
}
]
Where the source `users` directory already contained a `wking`
subdirectory.  So by the time the tmpfs was setup, the destination
directory would exist, but at validation time (without having run the
bind mount) the tmpfs destination directory would not exist.
The second (destination is a directory) errors on valid cases like:
"mounts": [
{
"source": "/etc/resolv.conf",
"destination": "/etc/resolv.conf",
"type": "bind"
}
]
because binding files to files …
=> validate: Drop mount checks

validate.go
=> validation: add hostname validation

man/ocitools-validate.1.md, validate.go
=> validate: add Hooks validation

cmd/runtimetest/main.go
=> runtimetest: add root filesystem validation

validate.go
=> validation: add env validation for hooks

validate.go
I think absolute path is clearer for users.
=> validate: small fix for root path error

cmd/runtimetest/main.go
=> runtimetest: add masked paths validation

validate.go
=> just check hostname with UTS namespace when platform set as linux

cmd/runtimetest/main.go
=> runtimetest: add readonly path validation

man/ocitools-generate.1.md
Fix the typo in the manual doc for `--mount` option inside `man/ocitools-generate.1.md`.
=> Fix typo in man/ocitools-generate.1.md

Godeps/Godeps.json, Godeps/_workspace/src/github.com/blang/semver/LICENSE, Godeps/_workspace/src/github.com/blang/semver/README.md, Godeps/_workspace/src/github.com/blang/semver/examples/main.go, Godeps/_workspace/src/github.com/blang/semver/json.go, Godeps/_workspace/src/github.com/blang/semver/json_test.go, Godeps/_workspace/src/github.com/blang/semver/range.go, Godeps/_workspace/src/github.com/blang/semver/range_test.go, Godeps/_workspace/src/github.com/blang/semver/semver.go, Godeps/_workspace/src/github.com/blang/semver/semver_test.go, Godeps/_workspace/src/github.com/blang/semver/sort.go, Godeps/_workspace/src/github.com/blang/semver/sort_test.go, Godeps/_workspace/src/github.com/blang/semver/sql.go, Godeps/_workspace/src/github.com/blang/semver/sql_test.go, validate.go
Use an off-the-shelf SemVer parser and error out if the config targets
an unsupported spec version.  Slightly more detail in the commit
messages ;).
=> validate: Improved version handling

cmd/runtimetest/main.go
find the process args issue when try commits in https://github.com/opencontainers/ocitools/pull/97
=> get process args by bytes.Split

test_runtime.sh
I've never run a system where an unprivileged user could create a new
root directory, so this avoids:
$ mkdir -p /testroot
mkdir: cannot create directory ‘/testroot’: Permission denied
I'm not entirely clear why the old code used /testroot.  It landed in
d3e2985 (Add a script to prepare a rootfs for testing, 2015-10-13),
but without additional motivation.  It's possible that it's related to
opencontainers/runc#710, but that was proposed much later
(2016-03-30).  And I'm not sure what the pivot problems were that runC
avoids with --no-pivot, since ccon has no problem pivoting from a
tmpfs:
$ pwd
/tmp/pivot-root
$ grep /tmp /proc/self/mounts
none /tmp tmpfs rw,relatime 0 0
$ jq .namespaces.mount.mounts config.json
[
{
"source": "rootfs",
"target": "rootfs",
"flags": [
"MS_BIND"
]
},
{ …
=> test_runtime.sh: Drop /testroot (falling back to $TMPDIR)

cmd/runtimetest/main.go, cmd/runtimetest/mount/LICENSE, cmd/runtimetest/mount/README.md, cmd/runtimetest/mount/mountinfo.go, cmd/runtimetest/mount/mountinfo_freebsd.go, cmd/runtimetest/mount/mountinfo_linux.go, cmd/runtimetest/mount/mountinfo_solaris.go, cmd/runtimetest/mount/mountinfo_unsupported.go, cmd/runtimetest/mount/mountinfo_windows.go
validate the runtime mount information by using docker/pkg/mount
and validate the rootfs readonly setting
=> Mount test 

cmd/runtimetest/main.go
=> runtimetest: add NoNewPriviledges validation

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/state.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go
=> Update runtime-spec dependency to v1.0.0-rc1

validate.go
env name should not begin with a digit
=> validate/env: add env name begins with digit check

test_runtime.sh
From [the spec][1]:
> **`path`** (string, required) Specifies the path to the root filesystem
>  for the container. A directory MUST exist at the path declared by
> the field.
From [POSIX][2]:
> The special filename dot shall refer to the directory specified by
> its predecessor.
Also from [POSIX][3]:
> #### Dot
>
> In the context of naming files, the filename consisting of a single
> `<period>` character ( `.` ).
Also from [POSIX][4]:
> #### Filename
>
> A sequence of bytes consisting of 1 to `{NAME_MAX}` bytes used to name
> a file… The filenames dot and dot-dot have special meaning.
Support for empty-string paths in the wild seems mixed.  Coreutils'
`realpath` complains:
$ realpath ''
realpath: ‘’: No such file or directory
$ realpath --version
realpath (GNU coreutils) 8.23
...
$ …
=> test_runtime.sh: Change --rootfs from '' to '.'

validate.go
When json sets null to slice type and does not have omitempty tag, the check should failed.
=> checkMandatory: fix slice check

completions/bash/ocitools, generate.go, man/ocitools-generate.1.md
=> generate: add new cgroup namespace option

cmd/runtimetest/main.go
=> runtime: add linux default fs validation

README.md, generate.go, man/ocitools-generate.1.md, test_runtime.sh
This makes it easier to post-process output before writing it to disk.  For example, you may want to make adjustments with jq and/or [write part of the configuration to a different file for consumption by non-OCI tools][1].
[1]: https://github.com/opencontainers/ocitools/pull/128#issuecomment-230580568
=> generate: Add --output=PATH and write to stdout by default

validate.go
=> validate: add sysctl check

completions/bash/ocitools, man/ocitools-validate.1.md, validate.go
=> validate: add mount type check

cmd/runtimetest/main.go
=> runtimetest: Fix check for device nodes

generate/generate.go
The PR adds functions setting the linux resource cpu and memory fields into the generate library.
=> Add resource set funcs into generate library

cmd/ocitools/validate.go
This PR removes two extra else {}. This makes the code clean, also stops vim-bundle complaining.
=> remove extra else

test_runtime.sh
The switch to `--output` in 06d61a34 (generate: Add `--output=PATH` and write to stdout by default, 2016-07-05, #129) was too narrow.  There's no need to change directories now that the output path is configurable.
=> test_runtime.sh: Drop pushd/popd from around 'generate'

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, generate/generate.go
The PR vendors the latest version of the runtime-spec package, and updates generate.go.
=> Update runtime-spec package

generate/generate.go, generate/spec.go
The PR tries to check whether a pointer field is `nil` before modifying the field. This avoids modifying the field of a `nil` pointer.
=> Check pointer fields of g.spec

Makefile
Backporting #145 to v1.0.0.rc1 following [the first procedure here][1].
[1]: https://github.com/opencontainers/ocitools/pull/140#issuecomment-234626841
=> Makefile: clean up compiled man page

cmd/ocitools/generate.go
Backporting #146 to v1.0.0.rc1 following [the first procedure here][1].
[1]: https://github.com/opencontainers/ocitools/pull/140#issuecomment-234626841
=> generate: remove unuseful default value for output

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go
The commit reference that landed in 2d0dbcf0 (Update runtime-spec dependency to v1.0.0-rc1, 2016-06-14, #110) was a few commits after the tag, but the v1.0.0.rc1 branch is aiming for compatibility with the tagged release (e.g. no -dev suffix on the generated version).
I am not very familiar with godep, so I stubled around for a bit to make this change and don't have a set of copy/paste steps to share here :p.
=> Godeps: Roll runtime-spec back to v1.0.0-rc1

cmd/ocitools/generate.go, cmd/ocitools/main.go, cmd/ocitools/validate.go, generate/generate.go, man/ocitools-validate.1.md, man/ocitools.1.md
The PR checks whether each cap inside `capability.List()` is <= `capability.CAP_LAST_CAP` before adding it into `finalCapList`.
This avoids add unsupported cap into `finalCapList`. For example, `CAP_AUDIT_READ` is added into  the kernel since Linux 3.16, and not supported on RHEL7.
=> Check CAP_LAST_CAP while setting privileged

generate/generate.go
Signed-off-by: masm <mashimiao.fnst@cn.fujitsu.com>
=> generate: fix capability.List() for cap_last_cap not exist

generate/generate.go
Backported #155 to v1.0.0-rc1 (cherry-pick applied cleanly).
=> generate: fix tmpfs adding based on manpage

generate/generate.go
Backported to v1.0.0.rc1 from 1371b52 #168 (cherry-pick applied cleanly).
=> generate: remove unnecessary spec initialization

cmd/ocitools/generate.go, generate/generate.go
This PR tries to make the generate API easier to use.  For example, instead of feeding a whole string to `AddAnnotation`, the new API allows the user to feed a key and a value to `AddAnnotation`.
Note: This PR does not touch any seccomp-relative function to avoid conflicts with Grant's work. 
=> Modify generate API

cmd/ocitools/generate.go, man/ocitools-generate.1.md
=> generate: optimize namespace setup log and fix manpage

Godeps/Godeps.json, Godeps/_workspace/src/github.com/urfave/cli/.gitignore, Godeps/_workspace/src/github.com/urfave/cli/.travis.yml, Godeps/_workspace/src/github.com/urfave/cli/CHANGELOG.md, Godeps/_workspace/src/github.com/urfave/cli/LICENSE, Godeps/_workspace/src/github.com/urfave/cli/README.md, Godeps/_workspace/src/github.com/urfave/cli/app.go, Godeps/_workspace/src/github.com/urfave/cli/context.go, Godeps/_workspace/src/github.com/urfave/cli/flag.go, Godeps/_workspace/src/github.com/urfave/cli/help.go, Godeps/_workspace/src/github.com/urfave/cli/runtests
The new version of urfave/cli supports Int64Flag and Uint64Flag.
These flag types are useful for setting cpu/mem resources.
=> update urfave/cli package

generate/generate.go
Same as #160, but targeting v1.0.0.rc1.
=> generate: Remove superfluous err check from Save

Godeps/Godeps.json, Godeps/_workspace/src/github.com/urfave/cli/.gitignore, Godeps/_workspace/src/github.com/urfave/cli/.travis.yml, Godeps/_workspace/src/github.com/urfave/cli/CHANGELOG.md, Godeps/_workspace/src/github.com/urfave/cli/LICENSE, Godeps/_workspace/src/github.com/urfave/cli/README.md, Godeps/_workspace/src/github.com/urfave/cli/app.go, Godeps/_workspace/src/github.com/urfave/cli/context.go, Godeps/_workspace/src/github.com/urfave/cli/flag.go, Godeps/_workspace/src/github.com/urfave/cli/help.go, Godeps/_workspace/src/github.com/urfave/cli/runtests
The new version of urfave/cli supports Int64Flag and Uint64Flag.
These flag types are useful for setting cpu/mem resources.
Backported to v1.0.0.rc1 from dc3404e #174 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] update urfave/cli package to v1.18.0

cmd/ocitools/generate.go, man/ocitools-generate.1.md
Backported to v1.0.0.rc1 from 15f529b #166 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] generate: optimize namespace setup log and fix manpage

completions/bash/ocitools
=> completions: update based on generate help message

completions/bash/ocitools
Backported to v1.0.0.rc1 from 2c278ff #167 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] completions: update based on generate help message

generate/generate.go
Backported to v1.0.0.rc1 from c4fb2c0 #156 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] generate: fix mount-cgroups bug

cmd/ocitools/generate.go, generate/generate.go, man/ocitools-generate.1.md
=> support setting oom_score_adj

cmd/ocitools/generate.go, generate/generate.go, man/ocitools-generate.1.md
Backported to v1.0.0.rc1 from 1915407 #176 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] support setting oom_score_adj

cmd/ocitools/generate.go, man/ocitools-generate.1.md
=> add label manpage and fix help

cmd/ocitools/validate.go
=> validation: add linux resource check

cmd/ocitools/validate.go
Backported to v1.0.0.rc1 from 9cad4d8 #195 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] validation: add linux resource check

cmd/ocitools/validate.go
=> add namespace check for uid/gid mappings

cmd/ocitools/generate.go, man/ocitools-generate.1.md
Backported to v1.0.0.rc1 from 5de50e5 #189 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] add label manpage and fix help

man/ocitools.1.md
Before this commit the latter was slightly more popular:
$ git grep '\*\*(1)' | wc -l
3
$ git grep '(1)\*\*' | wc -l
2
Change generated with:
$ sed -i 's/(1)\*\*/**(1)/g' $(git grep -l '(1)\*\*')
=> man/ocitools.1: Replace "**...(1)**" with "**...**(1)"

cmd/ocitools/generate.go, man/ocitools-generate.1.md
=> add new generate options for setting cpu/mem

cmd/ocitools/generate.go, man/ocitools-generate.1.md
Backported to v1.0.0.rc1 from 092cb7c6 #175 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] add new generate options for setting cpu/mem

cmd/ocitools/validate.go
=> validation: add check for namespace path

cmd/runtimetest/main.go
=> runtimetest: remove unnecessary else

cmd/runtimetest/main.go
Backported to v1.0.0.rc1 from 198ffb6 #158 (cherry-pick applied cleanly).
=> [1.0.0.rc1] Remove unnecessary else

cmd/oci-runtime-tool/validate.go
Backported to v1.0.0.rc1 from c8b8c73 #192 (cherry-pick applied
cleanly).
=> [1.0.0.rc1] validation: add check for namespace path

cmd/runtimetest/main.go
Backported to v1.0.0.rc1 from 609040b4 #208 (cherry-pick applied cleanly).
This builds on #215, so you can either:
a. Merge #215 and then consider this one.
b. Merge this one which will automatically close #215.
=> [1.0.0.rc1] runtimetest: remove unnecessary else

cmd/runtimetest/main.go
=> runtimetest: add linux devices validation

cmd/oci-runtime-tool/main.go
Backported to v1.0.0.rc1 from 8237430 #218 (cherry-pick applied cleanly).
=> [1.0.0.rc1] update command name and description

cmd/runtimetest/main.go
Backported to v1.0.0.rc1 from f0ae1dc #211 (cherry-pick applied cleanly).
=> [1.0.0.rc1] runtimetest: add linux devices validation

cmd/runtimetest/main.go
=> runtime: support oomScoreAdj validation

cmd/oci-runtime-tool/validate.go
=> validate: add hard and soft limit check for rlimit

.travis.yml
go 1.5.3 fails to run golint in 'travis' file.
Find the reason for this:
https://github.com/golang/lint/commit/a428635c58fe96360e83667e2e1a8343fc292bf0
=> use go > 1.5 since golint drop support for 1.5

cmd/oci-runtime-tool/validate.go
Add IsAbs check due to runtime spec changes:
https://github.com/opencontainers/runtime-spec/blob/master/config.md#root-configuration
=> check if Root.Path is Abs

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/spec.go, man/oci-runtime-tool-generate.1.md
=> generate: add pids limit support

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
=> generate: add OOM Killer disable support

cmd/runtimetest/main.go
=> runtime: support IDMappings validation

.travis.yml
Backported to v1.0.0.rc1 from f9096d89 #230 (cherry-pick applied cleanly).
=> [1.0.0.rc1] use go > 1.5 since golint drop support for 1.5

generate/generate.go
And a "priviledge" → "privilege" typo.  Both turned up by [Misspell][1] and [reported by Go Report Card][2].
[1]: https://github.com/client9/misspell
[2]: https://goreportcard.com/report/github.com/opencontainers/runtime-tools
=> generate/generate: Fix "specifed" → "specified" typo

cmd/runtimetest/main.go
Backported to v1.0.0.rc1 from 3d2cac7 #210 (cherry-pick applied cleanly).
=> [1.0.0.rc1] runtime: support oomScoreAdj validation

cmd/oci-runtime-tool/validate.go
Backported to v1.0.0.rc1 from f175fae0 #223 (cherry-pick applied cleanly).
=> [1.0.0.rc1] validate: add hard and soft limit check for rlimit

cmd/runtimetest/main.go
Backported to v1.0.0.rc1 from baf6c3bb #236 (cherry-pick applied cleanly).
=> [1.0.0.rc1] small fix: fomart variable as CamelCase

cmd/oci-runtime-tool/validate.go
Backported to v1.0.0.rc1 from a1ce2b1b #233 (cherry-pick applied cleanly).
=> [1.0.0.rc1] check if Root.Path IsAbs; using filepath instead of path

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/spec.go, man/oci-runtime-tool-generate.1.md
Backported to v1.0.0.rc1 from beb64787 #206 (cherry-pick applied cleanly).
=> [1.0.0.rc1] generate: add pids limit support

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Backported to v1.0.0.rc1 from 5caf782c #207 (cherry-pick applied cleanly).
=> [1.0.0.rc1] generate: add OOM Killer disable support

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/seccomp/consts.go, generate/seccomp/doc.go, generate/seccomp/parse_action.go, generate/seccomp/parse_architecture.go, generate/seccomp/parse_arguments.go, generate/seccomp/parse_remove.go, generate/seccomp/seccomp_default.go, generate/seccomp/syscall_compare.go, man/oci-runtime-tool-generate.1.md
I added functionality to specify syscalls and their arguments for all actions. Also changed default action and archs flags to ociseccompgen library. 
Now we can do things like:
`ocitools generate --seccomp-errno clone,write --seccomp-trace getcwd --seccomp-trap umount:0:1:2:NE`
The behavior mimics that of: https://github.com/GrantSeltzer/Manhattan
Also updated man page to reflect this change. 
Signed-off-by: Grantseltzer <grantseltzer@gmail.com>
=> Use seccomp library for adding seccomp configuration flags

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
=> generate: add maskedPaths and readonlyPaths options

.gitignore, Makefile
So we can build runtime_tools project anyway.
Signed-off-by: Qiang Huang h.huangqiang@huawei.com
=> Add RUNTIME_TOOLS_LINK in Makefile

cmd/oci-runtime-tool/generate.go, generate/generate.go, man/oci-runtime-tool-generate.1.md
This allows for the set of options to be more useful than just "rw" or
"ro". It also makes it match the AddTmpfsMount far more.
We should also probably implement `AddMount` which just simply
adds a mount.
Signed-off-by: Aleksa Sarai <asarai@suse.com>
=> generate: make AddBindMount() options a slice

generate/generate.go
And a "priviledge" -> "privilege" typo.  Both turned up by Misspell
[1](https://github.com/client9/misspell) and reported by Go Report Card [2](https://goreportcard.com/report/github.com/opencontainers/runtime-tools).
Backported to master from #251 
Signed-off-by: W. Trevor King wking@tremily.us
=> [Master] generate/generate: Fix "specifed" -> "specified" typo

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
After updated, options of rootfs will be more human-readable and easy to understand
=> generate: update rootfs releated options

validate/validate.go
=> validate: add maskedpaths and readonlypaths check

man/oci-runtime-tool-generate.1.md
=> man: fix description for rootfs

Godeps/Godeps.json, Godeps/_workspace/src/github.com/urfave/cli/.travis.yml, Godeps/_workspace/src/github.com/urfave/cli/CHANGELOG.md, Godeps/_workspace/src/github.com/urfave/cli/README.md, Godeps/_workspace/src/github.com/urfave/cli/app.go, Godeps/_workspace/src/github.com/urfave/cli/appveyor.yml, Godeps/_workspace/src/github.com/urfave/cli/cli.go, Godeps/_workspace/src/github.com/urfave/cli/command.go, Godeps/_workspace/src/github.com/urfave/cli/context.go, Godeps/_workspace/src/github.com/urfave/cli/errors.go, Godeps/_workspace/src/github.com/urfave/cli/flag-types.json, Godeps/_workspace/src/github.com/urfave/cli/flag.go, Godeps/_workspace/src/github.com/urfave/cli/flag_generated.go, Godeps/_workspace/src/github.com/urfave/cli/generate-flag-types, Godeps/_workspace/src/github.com/urfave/cli/help.go, Godeps/_workspace/src/github.com/urfave/cli/runtests, cmd/runtimetest/main.go
Cherry-picking #260 onto master.
=> cmd/runtimetest: Add an app description

cmd/oci-runtime-tool/generate.go
As mentioned in issue/#280, wihtout foramt description,
user may be confused to how to use --tmpfs
=> generate: add format description for --tmpfs

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
Allow generating configs with environment variables sourced from a file using the same syntax as docker.
Closes #275
=> Add docker-style --env-file flag support.

cmd/runtimetest/main.go
According to runtime SPEC, /dev/console will exist if Terminal is true
=> runtimetest: fix linux default devices validation

cmd/oci-runtime-tool/generate.go, generate/generate.go
If a given environment variable has already been set, replace the
variable rather than appending it to the environment list. This avoids
issues with POSIX (which doesn't define what to do with duplicate
values).
The method of determining whether a variable has been set is by checking
that the VAR_NAME= prefix of both strings is the same.
Fixes: #290
Signed-off-by: Aleksa Sarai <asarai@suse.de>
=> generate: replace duplicate env entries

cmd/runtimetest/main.go
avoid mount check failed because of not shortest path
=> runtimetest: clean filepath for mounts

generate/generate.go
Catch up with the in-flight opencontainers/runtime-spec@6323157 (specs-go/config: Make Linux and Solaris omitempty (again), 2016-06-17, opencontainers/runtime-spec#502).
The “does the marshaled JSON look like '{}'?” check is a pretty cheap trick, but it was the easiest way I could think of for “is there anything useful in here?”.  An alternative approach that conditionally added an `&rspec.Linux{}` only if needed seemed too tedious.
This should not land before opencontainers/runtime-spec#502, and it may not even be worth reviewing until then.  But I'd worked up the changes while testing the runtime-spec PR, so I thought I might as well push them in case other folks wanted to see how I'd tested it.
=> generate: Adjust to Spec.Linux being a pointer

validate/validate.go
According to [runtime-spec's platform.arch](https://golang.org/doc/install/source#environment),completion check type.
=> validate.go：Increase the type of checkplatform

cmd/runtimetest/main.go
=> runtimetest: add linux default symbolic link validation

cmd/oci-runtime-tool/generate.go
if rlimits-remove-all or seccomp-remove-all is set to false, generate still call
Clear* function, we should forbid it.
=> generate: fix *-remove-all parse bug

validate/validate.go
According to the [specification](https://github.com/opencontainers/runtime-spec/blame/master/config.md#L49-L50).
=> validate:Increase the destination path judgment

Godeps/Godeps.json, Godeps/_workspace/src/github.com/mndrix/tap-go/.gitignore, Godeps/_workspace/src/github.com/mndrix/tap-go/LICENSE, Godeps/_workspace/src/github.com/mndrix/tap-go/Makefile, Godeps/_workspace/src/github.com/mndrix/tap-go/README.md, Godeps/_workspace/src/github.com/mndrix/tap-go/tap.go, cmd/runtimetest/main.go
This gets us to this output:
```
-----------------------------------------------------------------------------------
VALIDATING RUNTIME: runc
-----------------------------------------------------------------------------------
TAP version 13
ok 1 - root filesystem
ok 2 - hostname
ok 3 - mounts
ok 4 - capabilities
ok 5 - default symlinks
ok 6 - default file system
ok 7 - default devices
ok 8 - linux devices
ok 9 - linux process
ok 10 - masked paths
ok 11 - oom score adj
ok 12 - read only paths
ok 13 - rlimits
ok 14 - sysctls
ok 15 - uid mappings
ok 16 - gid mappings
Runtime runc passed validation
```
@hqhq @Mashimiao @wking @liangchenye PTAL
=> Tap output from runtime test

cmd/oci-runtime-tool/generate.go, man/oci-runtime-tool-generate.1.md
It's valid for values to start with '=' .
=> generate: fix annotations parse

completions/bash/oci-runtime-tool
Both `__oci-runtime-tool_complete_seccomp_arches` and `__oci-runtime-tool_complete_arches` just fill `$COMPREPLY` and output nothing.
We should not use their output to reset `$COMPREPLY` in `_oci-runtime-tool_generate`.
This patch prevent the "reset" operation, and fix the bug.
=> fix bug for --arch and --seccomp-arch in bash completion

completions/bash/oci-runtime-tool
These architectures are added in "[2d0dbcf: Update runtime-spec dependency to v1.0.0-rc1"](https://github.com/opencontainers/runtime-tools/commit/2d0dbcf085e1e08fd05b16b6efb2b6e9336594e7#diff-ede289fca06f6891ce7eaa945805e086R425).
This patch adds them into bash-completion.
=> bash-completion: add more architectures

validate/validate.go
=> validate: add args validation

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
generate a device section in config.json.
Example
oci-runtime-tool generate --device c:10:229:/dev/fuse:fileMode=438:uid=0:gid=0  --device b:8:0:/dev/sda:fileMode=438:uid=0:gid=0
According to [Devices.](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#devices)
Signed-off-by: Zhai Zhaoxuan <zhaizx.fnst@cn.fujitsu.com>
=> generate: add device option

cmd/runtimetest/main.go
A process will not always be pid 1  if we are not unsharing pid namespace or we are entering an existing one.
=> Use current process pid instead of assuming pid 1

cmd/oci-runtime-tool/validate.go, generate/generate.go, validate/validate.go
By now, if we generate with option --priviliged, the validation of bundle will fail.
capabilities need to be more than original defaultCap has.
=> validate: optimize capabilites check

cmd/runtimetest/main.go
According to spec, defaultFS is not MUST any more
=> cleanup: remove defaultfs validaton

validate/validate.go
I think we should increase the judgment of several OS.
https://github.com/opencontainers/runtime-spec/blame/master/config.md#L324
=> validate.go add checkos

MAINTAINERS
On Tue, 7 Mar 2017 at 11:57-0800, @LK4D4 [wrote][1]:
> Hello, I'd like to resign from all OCI roles which were assigned to me because I don't work with containers anymore.
[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/JvN8jWhS55c
=> MAINTAINERS: Remove Alexander

validate/validate.go
According to [this](https://github.com/opencontainers/runtime-spec/blame/master/config.md#L149).
=> validate: add the verification content

validate/validate.go
=> validate: add network host-specific check

completions/bash/oci-runtime-tool
According to the runtime-spec, the values which can be accept by --arch
are listed in the Go Language document for $GOARCH.
I found [the list](https://golang.org/doc/install/source#environment), and added some missed values
=> bash-completion: add some architectures.

validate/validate.go
=> validate: add namespace if is duplicated check

validate/validate.go
Test the [spec's][1]:
> While these artifacts MUST all be present in a single directory on the local filesystem, …
which is a condition it imposes on `config.json` and the directory referenced by `root.path`.
I think we should drop that restriction from the spec, but [my attempt to remove the restriction was rejected][2].  If a future spec drops the restriction, we can revert this commit.
Using `path/filepath` for the path manipulation will break when validating cross-platform configs (e.g. trying to validate a Windows bundle on a Linux machine).  But that's a bigger issue than this commit (previous discussion [here][3] and [here][4]), so I've left it alone for now.
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc5/bundle.md#container-format
[2]: …
=> validate: Test config.json and rootfs sibling-hood

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/state.go, Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go, Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go, cmd/oci-runtime-tool/generate.go, cmd/runtimetest/main.go, generate/generate.go, generate/seccomp/parse_action.go, generate/seccomp/parse_architecture.go, generate/seccomp/parse_arguments.go, generate/seccomp/parse_remove.go, generate/seccomp/seccomp_default.go, generate/seccomp/syscall_compare.go, generate/spec.go, validate/validate.go
Update the `runtime-spec` version, some corresponding change questionable, what questions please suggest.
=> update runtime-spec version

completions/bash/oci-runtime-tool, validate/validate.go
Change by https://github.com/opencontainers/runtime-spec/pull/705.
=> Add valid seccomp arch

validate/validate.go
For some of the [linux system](https://github.com/opencontainers/runtime-spec/blame/master/config.md#L145) under the special value of the verification, should increase the decision on the `os`.
=> validate: increase OS validation for special cases

validate/validate.go
Fixes the following issue:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ce0c9]
goroutine 1 [running]:
panic(0x5ad320, 0xc4200120a0)
/usr/lib64/go/src/runtime/panic.go:500 +0x1a1
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckHooks(0xc4200b77b8, 0xc420084d80, 0x0, 0x0)
/home/abuild/rpmbuild/BUILD/go/src/github.com/opencontainers/runtime-tools/validate/validate.go:203 +0x89
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckAll(0xc4200b77b8, 0x26, 0x0, 0xc4200aa000)
/home/abuild/rpmbuild/BUILD/go/src/github.com/opencontainers/runtime-tools/validate/validate.go:109 +0x582
main.glob..func2(0xc4200a2140, 0x0, 0x20000c4200a2140) …
```
=> validate: fix spec.Hooks nil dereference

generate/seccomp/parse_architecture.go
=> generate/seccomp/parse_architecture: Add parisc(64) to parseArch

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com
=> add device-remove and device-remove-all option

validate/validate.go
Because of the changes in #220, delete the extra `defaultCaps`.
=> validate: delete the extra defaultCaps

generate/generate.go
commit afc8d3588cbf9c5de0be4ab00d352077be78a0d3 updated the
runtime-spec version but introduced a bug when dropping capabilities.
If you drop a capability it will only be dropped in the Bounding
capabilities set while kept in the other sets.
This causes a bug when using the generated config.json in which
containers cannot be started at all.
This patch fixes the above by dropping `return nil` statements.
@mrunalp @Mashimiao PTAL asap
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> generate: drop caps in every cap set

validate/validate.go
Solve the following questions：
> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x4d29be]
goroutine 1 [running]:
panic(0x5ac0e0, 0xc420012100)
/home/zhouhao/go/src/runtime/panic.go:500 +0x1a1
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckLinux(0xc42004f7c8, 0xc4200a80c0, 0x0, 0x2)
/home/zhouhao/runtime-tools/Godeps/_workspace/src/github.com/opencontainers/runtime-tools/validate/validate.go:436 +0x41e
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckAll(0xc42004f7c8, 0x1, 0x0, 0xc4200a4000)
/home/zhouhao/runtime-tools/Godeps/_workspace/src/github.com/opencontainers/runtime-tools/validate/validate.go:92 +0x4d2
main.glob.func2(0xc4200a2140, 0x0, 0x20000c4200a2140) …
=> validate: fix spec nil dereference

validate/validate.go
So folks adding new mips* entries don't have to agonize over where to put them ;).
Earlier discussion [here][1].
[1]: https://github.com/opencontainers/runtime-tools/pull/368#discussion_r112497741
=> validate: Alphabetize arch entries for Linux

validate/validate.go
According to the  [shared subtree](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt).
=> validate: modify the valid value of rootfsPropagation

cmd/runtimetest/main.go
If we don't use pid namespace, the process's pid will not be 1
=> use current pid instead of 1

generate/generate.go, generate/spec.go
Before modifying the spec's Hooks, check if the Hooks structure itself needs to be allocated.
=> generate: initialize the Hooks pointer

cmd/runtimetest/main.go
As we used test framework, debug info is not needed any more.
=> remove unneeded debug info

man/oci-runtime-tool-generate.1.md
=> add warning for template option

cmd/oci-runtime-tool/generate.go
=> generate: enhance options parse

.travis.yml, Makefile, validate/validate_test.go
Signed-off-by: liangchenye <liangchenye@huawei.com>
=> add CheckSemVer, CheckRootfsPath, CheckPlatform unit test

Makefile, cmd/oci-runtime-tool/generate.go, cmd/oci-runtime-tool/main.go, cmd/oci-runtime-tool/validate.go, cmd/runtimetest/main.go, generate/generate.go, man/oci-runtime-tool-generate.1.md, man/oci-runtime-tool.1.md, validate/validate.go, validate/validate_test.go, validation/validation_test.go
=> Remove platform

Makefile
We used to use this option but it's reverted
in #231 , not sure about the reason, it's simpler
than to use the OUT hack.
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
=> Makefile: use -set_exit_status for golint

cmd/oci-runtime-tool/main.go, cmd/oci-runtime-tool/validate.go, man/oci-runtime-tool-validate.1.md, man/oci-runtime-tool.1.md, validate/validate.go
Signed-off-by: liangchenye <liangchenye@huawei.com>
=> overwrite the 'platform' value  when 'host-specific' was set

Makefile, cmd/oci-runtime-tool/main.go
It make user know more information about `oci-runtime-tool`.
=> Add commit to version info

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
Since in https://github.com/opencontainers/runtime-tools/issues/343#issuecomment-286005046 @Kxuan  put forward the idea, I submitted this PR.
=> generate: rectify the arguments

Godeps/Godeps.json, vendor/github.com/syndtr/gocapability/capability/capability_linux.go
This patch updates the gocapability vendor package [1] so as not to
fail the ambient capability test case which 'make localvalidation'
invokes.
[1] Fix issue #12: break too early #13
https://github.com/syndtr/gocapability/pull/13
Signed-off-by: Naohiro Tamura <naohirot@jp.fujitsu.com>
=> Fix ambient capability test case

man/oci-runtime-tool-generate.1.md
In #371, the old `--mount-label` and `--selinux-label` became `--linux-mount-label` and `--linux-selinux-label`.  However, the `--mount-label` use in this example wasn't updated and the `--selinux-label` use was incorrectly updated to `--process-selinux-label`.  This commit brings the example back in line with the program source.
I've also added backticks around `--linux-selinux-label` to get better formatting for the [inline code][1].
There are also #371 fixups in flight with #418, but this PR is touching a different file.
[1]: https://daringfireball.net/projects/markdown/syntax#code
=> man/oci-runtime-tool-generate.1: Fix --mount-label and --process-selinux-label

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
Which was missed in #371.
Also fix:
* `--cwd` → `--process-cwd` (missed in #371)
* `--rootfs` → `--rootfs-path` (missed in #254)
=> *: Fix --bind -> --mount-bind, etc.

validate/validate.go
Signed-off-by: liangchenye <liangchenye@huawei.com>
=> platform config could exist even platform is different

cmd/runtimetest/main.go
Even if bind mount succeed, there will not any bind or rbind key word
in type of options of mount.
So, we can not make sure if bind mount succeed.
It'd better to skip bind mount check
=> runtimetest: fix mounts check

.pullapprove.yml
=> update pullapprove config

completions/bash/oci-runtime-tool, generate/seccomp/parse_action.go, generate/seccomp/parse_remove.go, man/oci-runtime-tool-generate.1.md
1. completion for --seccomp-default is not correct, need to fix it and manpage.
2. There is no need to call parseAction() twice, we can pass type rspec.LinuxSeccompAction directly.
3. There is no need to distinguish whether string contains ',' or not, split can handle them.
=> fix seccomp-default parse and remove problem

generate/seccomp/seccomp_default.go
duplicated caps will generate duplicated syscalls.
We should avoid that.
=> remove duplicated caps for syscalls

Godeps/Godeps.json, cmd/oci-runtime-tool/generate.go, generate/generate.go, vendor/github.com/opencontainers/runtime-spec/LICENSE, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/state.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
@opencontainers/runtime-tools-maintainers PTAL
=> Bump up runtime-spec dependency to v1.0.0

cmd/runtimetest/main.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool.1.md, validate/error.go
this is an implementation of #353 .
PTAL
@wking @Mashimiao @mrunalp
=> add OCIError to differentiate 'MUST/SHOULD' and add reference support

validate/validate.go, validate/validate_test.go
1. CheckRootfsPath does not only include Path check, we should rename it.
2. For Hyper-V container, Root must not be set.
=> Rename CheckRootfsPath and add Root check for hyper-v

validate/validate.go
```
➜  runtime-tools git:(master) ✗ ./oci-runtime-tool validate --platform windows 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4cf70d]
goroutine 1 [running]:
panic(0x5aeb80, 0xc4200100f0)
/home/zhouhao/go/src/runtime/panic.go:500 +0x1a1
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckRoot(0xc4200b77b0, 0xc4200c4610, 0x1, 0x1)
/home/zhouhao/workspace/Go/src/github.com/opencontainers/runtime-tools/validate/validate.go:114 +0xf6d
github.com/opencontainers/runtime-tools/validate.(*Validator).CheckAll(0xc4200b77b0, 0x1, 0x0, 0xc420010ab1)
/home/zhouhao/workspace/Go/src/github.com/opencontainers/runtime-tools/validate/validate.go:99 +0xb2
main.glob.func2(0xc4200a4140, 0x0, …
```
=> validate: avoid panic on nil fields

cmd/runtimetest/main.go, error/error.go, validate/error.go
As discussed [here][1].  This makes it easier for other projects (e.g. image-tools) to use the same tooling if they want.  Some components of the old `validate/error.go` were runtime-spec-specific (e.g. the reference template and `ociErrors`), so they've stayed in the validate package.
I've also expanded `NewError` to take an explicit version (as requested [here][2]).  That allows us to link to the proper spec even if we're capable of validating several spec versions (e.g. 1.0 and 1.1 configurations or runtimes).
[1]: https://github.com/opencontainers/runtime-tools/pull/354#discussion_r109216291
[2]: https://github.com/opencontainers/runtime-tools/pull/354#discussion_r108980617
=> error: Pull the RFC 2119 error representation into its own package

validate/validate.go
duplicated device path is invalid
duplicated major:minor is not recommended
=> validate: enhance linux devices validation

validate/validate.go
#297 causes this bug, maybe it hasn't been update for a long time, we didn't find out this bug before merged.
=> validate/validate.go: fix duplicated variable bug

Makefile
And also set `-installsuffix cgo`.  `runtimetest` is designed to be run from inside a container, which may include a mount namespace that has no linker or dynamic libraries.  These changes give us a static runtimetest binary which will work in those conditions.
The approach I'm using here follows [this suggestion][2].  RunC does things a bit differently (see opencontainers/runc#401), but I'm not familiar enough with Go to contrast the approaches.
[2]: https://github.com/golang/go/issues/9344#issuecomment-69944514
=> Makefile: Set CGO_ENABLED=0 for runtimetest

validate/validate.go
=> validate: add mounts whether nested check

validate/validate.go
According to the following spec：
[devices.type](https://github.com/opencontainers/runtime-spec/blame/master/config-linux.md#L218)
[devices.access](https://github.com/opencontainers/runtime-spec/blame/master/config-linux.md#L222-L223)
=> validate: add the validation of Resources.devices

error/runtime_spec.go, validation/container.go, validation/validation_test.go
=> add 'Runtime' struct to make test easier; add create test

cmd/runtimetest/main.go
According to mount orders in /proc/self/mountinfo to validate whether mounts are mounted in order.
=> runtimetest: add mounts order validation

cmd/runtimetest/main.go, error/error.go, specerror/error.go, validate/validate.go, validate/validate_test.go, validation/validation_test.go
With #437, I'd created a package that was completely independent of runtime-spec.  As I pointed out in that PR, this made it possible for image-tools and other projects to reuse the generic RFC 2119 handling (which they care about) without involving the runtime-spec-specific error enumeration and such (which they don't care about).
In #451, some runtime-spec-specific functionality leaked into the error package.  I'd recommended [keeping configuration and runtime requirements separate][1], because you're unlikely to be testing both of those at once.  But @liangchenye [wanted][2] them [collected][3].  And the `NewError` and `FindError` utilities would be the same regardless of target, so that's a good argument for keeping them together.  This commit moves the runtime-spec-specific …
=> specerror: Pull runtime-spec-specific error handling into its own package

cmd/runtimetest/main.go
Also increase the error message detail and continue through the remaining mounts instead of breaking on the first missing/misordered mount.  Based on previous discussion [here][1] and [here][2].  With this commit, a configuration like:
```
"mounts": [
{
"destination": "/tmp",
"type": "tmpfs",
"source": "none"
},
{
"destination": "/tmp",
"type": "tmpfs",
"source": "none"
},
{
"destination": "/dev",
"type": "devtmpfs",
"source": "devtmpfs"
}
]
```
and mountinfo like:
```
$ grep -n '/dev \|/tmp ' /proc/self/mountinfo
2:19 17 0:6 / /dev rw,nosuid,relatime - devtmpfs devtmpfs rw,size=10240k,nr_inodes=2043951,mode=755
25:41 17 0:38 / /tmp rw,relatime - tmpfs none rw
```
will generate errors like:
```
* mounts[1] {/tmp tmpfs none []} does not exist
* mounts[2] {/dev devtmpfs devtmpfs []} is …
```
=> cmd/runtimetest/main.go: Unify validateMountsExist and validateMountsOrder

generate/generate.go, validate/validate.go
This patch fixes two things:
- do not share slice between caps sets or otherwise you get lots of
troubles when playing with add/drop and slices... (slices are references...)
- fix cap add by effectively adding caps to all sets...
@mrunalp PTAL asap
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> generate: fix cap add/drop and initialize in privileged mode

generate/generate.go
There's actually little value in erroring out when asked to drop a
capability not supported on a system. This patch simply removes the cap
validation and just go ahead and drop the capability.
@mrunalp @Mashimiao PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> generate: do not validate caps when being dropped

validate/validate.go
Modify the following error situation:
```
✗ oci-runtime-tool validate 
0 errors occurred:
```
=> cmd: modify the err judgment

validate/validate_test.go
Without this, tests that expect an error tried to cast the `nil` to a multierror (which failed) and then tried to format a failure message with `errs.Error()` (which panicked).
=> validate/validate_test: Handle JSON Schema test not raising an error

validate/validate_test.go
Instead of raising messages like:
```
Error:  Not equal:
expected: <nil>(<nil>)
actual:
*multierror.Error(*multierror.Error{Errors:[]error{(*errors.errorString)(0xc42037adc0)},
ErrorFormat:(multierror.ErrorFormatFunc)(nil)})
```
raise messages like:
```
* linux.rootfsPropagation: linux.rootfsPropagation must be one of
the following: "private", "shared", "slave", "unbindable"
```
=> validate/validate_test: Better error messages for unexpected JSON Schema errors

generate/generate.go, validate/validate.go, validate/validate_test.go
According to the [spec.](https://github.com/opencontainers/runtime-spec/blame/master/config.md#L37)
>On Windows, path MUST be a volume GUID path.
=> validate: add root.path validation when platform is windows

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
The management of each field of the specific Capabilities.
=> Specific cap-add and cap-drop command

validate/validate.go
This is specific [spec](https://github.com/opencontainers/runtime-spec/blame/master/config.md#L167-L173).
Should increase the validation of `rlimit.type` on `solaris` system.
=> validate: add the validation of rlimit.type when platform is solaris

validate/validate.go
So don't duplicate those values.  Also drop `RLIMIT_LOCKS`, which [the man page documents as an obsolete-by-Linux-2.6 value][1].  A quick way to get a set of strings from the man page is:
$ curl -s 'https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/plain/man2/getrlimit.2?h=man-pages-4.13' |
>   sed -n 's/^\.BR\? \(RLIMIT_[^ ]*\)/\1/p' | sort | uniq
Also rename the old `default*Rlimits`, because these are valid-value arrays, not defaults.
Following up on the just-merged #461.
[1]: https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/getrlimit.2?h=man-pages-4.13#n209
=> validate/validate: Linux rlimits extend the POSIX rlimits

validate/validate_test.go
To demonstrate that this is covered by the 1.0.0 JSON Schema checks, and show that the omitempty protects us from errors for empty-string values despite there being no empty-string entry in [the JSON Schema][1].
These tests are in support for #473.
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0/schema/defs-linux.json#L4-L11
=> validate/validate_test: Add linux.rootfsPropagation checks

validate/validate.go
Accord to the [mknod(1)](http://man7.org/linux/man-pages/man1/mknod.1.html). We can get the following information:
> Both MAJOR and MINOR must be specified when TYPE is b, c, or u, and they must be omitted when TYPE is p.
=> validate: modify the condition of the deviceValid

cmd/oci-runtime-tool/main.go, cmd/runtimetest/main.go
This release covers almost all validation items for OCI bundle, contains the following changes since v0.1.0:
894cae7 validate/validate: Linux rlimits extend the POSIX rlimits
4f756fd Specific cap-drop command
ea55f9d Specific cap-add command
5cb6c48 rootfs.tar.gz: Bump to BusyBox 1.25.1
1a9532e generate: remove redundant content
567f1aa validate: add root.path validation when platform is windows
2cbb341 validate/validate_test: Add linux.rootfsPropagation checks
6e7da81 validate/validate_test: Better error messages for unexpected JSON Schema errors
4a705c6 validate/validate_test: Handle JSON Schema test not raising an error
16be985 validate: Delete the extra validation
3935592 Godeps: Include github.com/xeipuuv/gojsonschema
6e940f8 …
=> release: v0.2.0

CHANGELOG.md
Documenting the changes between v0.1.0 and v0.2.0, since these [didn't land as part of the release][1].
[1]: https://github.com/opencontainers/runtime-tools/pull/483#issuecomment-332078714
=> CHANGELOG: Document changes since v0.1.0

Makefile, filepath/abs.go, filepath/abs_test.go, filepath/ancestor.go, filepath/ancestor_test.go, filepath/clean.go, filepath/clean_test.go, filepath/doc.go, filepath/join.go, filepath/separator.go, validate/validate.go
As discussed [here][0] and later, and based on the Gist I'd created for that comment.
Go's path/filepath has lots of useful path operations, but there is a compile-time decision to select only the logic that applies to your `$GOOS`.  That makes it hard to validate a Windows config from a Linux host (or vice versa) because Go's builtin tools won't tell you whether a path is absolute on the target platform (just whether the path is absolute on *your* platform).  This commit adds a new package to do the same sorts of things but with an explicit OS argument.
In some cases, there's also an explicit workding directory argument. For example, Go's [`Abs`][1] has:
> If the path is not absolute it will be joined with the current working directory to turn it into an absolute path.
but that doesn't …
=> filepath: Add a stand-alone package for explicit-OS path logic

cmd/oci-runtime-tool/main.go, cmd/oci-runtime-tool/validate.go, man/oci-runtime-tool.1.md, specerror/error.go
The man-page entry and Bash completions for this option were added in 4029999d (#354), but the option was left unimplemented.  The implementation in this commit is very similar to the existing runtimetest implementation from 4029999d, except we warn instead of silently skipping non-fatal spec violations (more on that [here][1]).
The warning (vs. error) on invalid level arguments follows the runtimetest implementation from 6316a4e0 (#354).  I'd personally prefer hard errors on invalid level arguments, but didn't want to break runtime-tools consistency over that.
[1]: https://github.com/opencontainers/runtime-tools/pull/354#discussion_r110955465
=> cmd/oci-runtime-tool: Implement --compliance-level

cmd/runtimetest/main.go, generate/generate.go
=> fix nil deference

cmd/runtimetest/main.go, specerror/bundle.go, specerror/config-linux.go, specerror/config.go, specerror/error.go, specerror/runtime.go, validate/validate.go, validate/validate_test.go, validation/validation_test.go
=> rebase the specerror framework ; complete rfc code of config.md

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
These options allow user to configures the device whitelist.
Usage:
```
oci-runtime-tool generate \
--linux-device-cgroup-remove=deny,access=rwm \
--linux-device-cgroup-add=allow,type=c,major=10,minor=229,access=rw \
-linux-device-cgroup-add=allow,type=b,major=8,minor=0,access=r
```
Closes #314 
This is a rebase of #314 
Signed-off-by: Zhai Zhaoxuan <zhaizx.fnst@cn.fujitsu.com>
=> generate: add --linux-device-cgroup-add and --linux-device-cgroup-remove

completions/bash/oci-runtime-tool, generate/generate.go
=> fix rootfs-propagation

validate/validate.go
=> validate: fix cap validation

generate/generate.go, validate/validate.go, validation/generate_test.go
According to the spec, an unset .Type field in the
.Linux.Resources.Devices list is permitted (and it maps to "all").
This was broken recently, making our own default profile (as well as
umoci's and runc's) not pass validation anymore.
Signed-off-by: Aleksa Sarai <asarai@suse.de>
=> validate: allow unset "type" fields in resource devices whitelist

specerror/config.go, validate/validate.go, validate/validate_test.go
This PR builds on #480; review that first.
The spec isn't particuarly clear on this, [saying][1]:
> * Linux: valid values are defined in the `getrlimit(2)` man page, such as `RLIMIT_MSGQUEUE`.
> * Solaris: valid values are defined in the `getrlimit(3)` man page, such as `RLIMIT_CORE`.
[and][2]:
> For each entry in `rlimits`, a `getrlimit(3)` on `type` MUST succeed.
It doesn't say:
> Linux: The value MUST be listed in the `getrlimit(2)` man page…
and it [doesn't require the runtime to support the values listed in the man page][4] (opencontainers/runtime-spec#813).  So there are three sets:
* Values listed in the man page
* Values supported by the host kernel
* Values supported by the runtime
And as the spec stands, these sets are only weakly coupled, and any of them could be a sub- or …
=> validate: Soften unrecognized rlimit types to SHOULD violations

cmd/runtimetest/main.go, validate/validate.go, validate/validate_test.go
=> translate more RFC errors based on specerror

cmd/runtimetest/main.go, validate/validate.go
=> translate RFC errors

specerror/bundle.go, specerror/config-linux.go, specerror/config-windows.go, specerror/config.go, specerror/error.go, specerror/runtime-linux.go, specerror/runtime.go
Currently, error code is string type and duplicate with comment.
I think that's not good, we should change it.
=> redefine error code as int64

cmd/runtimetest/main.go
This isn't a question of not being implemented yet.  Windows [does not, and is unlikely to ever, support rlimits][1].  And the spec [only defines `process.rlimits` for POSIX platforms][2].  Folks writing Windows configs will only be setting `process.rlimits` as an out-of-spec extention.  We, as runtime validators, are unlikely to write such configs.  But if we use `runtimetest` in a container launched from such a config, we should silently ignore that out-of-spec extention, just like we silently ignore all other out-of-spec extentions, instead of logging a warning.
Previous discussion of this issue in the config-validation context [here][3].
[1]: https://github.com/opencontainers/runtime-spec/pull/835#issuecomment-303455386
[2]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0/co …
=> runtimetest: Make validateRlimits silent on Windows

cmd/runtimetest/main.go
This is a bit tricky, because before we load the config, we don't know the target spec version.  If a future spec version relaxes the current requirement, we'll have adjust runtimetest to tell it what version it's testing (where I've currently hard-coded 1.0.0).
=> runtimetest: Raise ConfigInRootBundleDir for missing config.json

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
=> generate: change process-tty to process-terminal

cmd/runtimetest/main.go, validation/validation_test.go
=> add more test cases for default runtime validation

cmd/runtimetest/main.go, validation/validation_test.go
=> runtimetest: add rootfs propagation test

cmd/runtimetest/main.go
=>  runtimetest: add posixValidations

cmd/runtimetest/main.go
=> runtimetest: add host platform validation

generate/generate.go
=> generate: fix DropProcessCapability*

cmd/runtimetest/main.go
=> runtimetest: fix nil dereference

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
As discussed in #470, there is not suitable separators for hooks.
Because of path may contains them.
So, decide to support json value for hooks.
=> support json value for hooks

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Add support for adding additional mounts.
Users can add custom additional mounts, like adding tmpfs without special options or with custom options.
=> generate:  support adding additional mounts for container

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/spec.go, man/oci-runtime-tool-generate.1.md
=> generate: support blkio related options

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/spec.go, man/oci-runtime-tool-generate.1.md
=> generate: add linux-intelRdt-l3CacheSchema option

validation/linux_gid_mappings.go, validation/linux_uid_mappings.go
If we want to apply idmappings, container need new user namespace
=> fix idmappings test

cmd/oci-runtime-tool/generate.go, man/oci-runtime-tool-generate.1.md
In my option, there is not any other good ways to solve conflicting
options problem except adding note for warning.
=> generate: solve conflicting options problem

generate/generate.go
Using non-null validation makes the code more efficient.
=> generate: Use non-null validation instead of initialization

validate/validate.go
1.Capabilities only support linux-based systems, so verification functions should not be called on other systems.
2.Hooks only support  POSIX platforms.
3.add a double guards to the call of the verification function
* Internally, raise an error if you call a check function for a platform that doesn't define the checked property 
* Externally, only call check functions on the appropriate platforms.
=> validate: modify the non-conforming validation

validate/validate.go
1. the limit depends on different kernel version and not definitely required by spec
=> Fix id mappings

validate/validate_test.go
There are some waiting improvements for the validation of the `mounts`, and the test function can be added later.
=> validate_test: add test func

validate/validate.go
These fields have already been verified in `CheckJSONSchema`, so there is no need to verify again.
Avoid the following duplicate error message:
```
2 errors occurred:
* linux.seccomp.architectures.2: linux.seccomp.architectures.2 must be one of the following: "SCMP_ARCH_X86", "SCMP_ARCH_X86_64", "SCMP_ARCH_X32", "SCMP_ARCH_ARM", "SCMP_ARCH_AARCH64", "SCMP_ARCH_MIPS", "SCMP_ARCH_MIPS64", "SCMP_ARCH_MIPS64N32", "SCMP_ARCH_MIPSEL", "SCMP_ARCH_MIPSEL64", "SCMP_ARCH_MIPSEL64N32", "SCMP_ARCH_PPC", "SCMP_ARCH_PPC64", "SCMP_ARCH_PPC64LE", "SCMP_ARCH_S390", "SCMP_ARCH_S390X", "SCMP_ARCH_PARISC", "SCMP_ARCH_PARISC64"
* seccomp architecture "SCMP_ACH_X32" is invalid
```
=> validate: remove duplicate verification

cmd/oci-runtime-tool/validate.go, man/oci-runtime-tool-validate.1.md, validate/validate.go, validate/validate_test.go
Fixes #414 
I'm wondering if it's necessary to change the default value of the `--platform` to the host platform.
=>  Add validation when host-specific is set 

cgroups/cgroups.go, cgroups/cgroups_v1.go, cgroups/cgroups_v2.go, validation/linux_cgroups_blkio.go, validation/linux_cgroups_cpus.go, validation/linux_cgroups_hugetlb.go, validation/linux_cgroups_memory.go, validation/linux_cgroups_network.go, validation/linux_cgroups_pids.go, validation/linux_cgroups_relative_blkio.go, validation/linux_cgroups_relative_cpus.go, validation/linux_cgroups_relative_hugetlb.go, validation/linux_cgroups_relative_memory.go, validation/linux_cgroups_relative_network.go, validation/linux_cgroups_relative_pids.go, validation/util/test.go
=> runtimetest: add validation of cgroups

cmd/oci-runtime-tool/generate.go, generate/generate.go
AddMount should also take a rspec.Mount object rather then a json string.
We are using generate as a library not using the command line tool.
The tool should translate the json into a rspec.Mount.
=> AddMounts should be AddMount you are only adding a single Mount

generate/generate.go
Current root propagation code does not allow rslave, rshared, runbindable and rprivate.
These are all legal proagations and should be allowed.
Also added the "bad" propagation flag to the error to make diagnosis easier.
=> Recursive propagation flags should be legal to use

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/spec.go, man/oci-runtime-tool-generate.1.md
Add some options to generate solaris application container configuration
Signed-off-by: Zhou Hao zhouhao@cn.fujitsu.com
=> generator solaris application container configuration

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, generate/generate_test.go, man/oci-runtime-tool-generate.1.md
We want to add a mount point to /dev/shm using the default spec,
but we don't want to mount /dev/shm via a tmpfs and then add our mountpoint
over it.
RemoveMount will remove a mount point based on the Destination, if it exists.
Does not return any error if the mount point does not exist.  Also added
Mounts() interface so that I could populate a test for new feature. Returns
the list of mounts.
=> Add interface to remove mounts.

validation/linux_cgroups_blkio.go, validation/linux_cgroups_cpus.go, validation/linux_cgroups_hugetlb.go, validation/linux_cgroups_memory.go, validation/linux_cgroups_network.go, validation/linux_cgroups_pids.go, validation/linux_cgroups_relative_blkio.go, validation/linux_cgroups_relative_cpus.go, validation/linux_cgroups_relative_hugetlb.go, validation/linux_cgroups_relative_memory.go, validation/linux_cgroups_relative_network.go, validation/linux_cgroups_relative_pids.go, validation/test-yaml, validation/util/linux_resources_blkio.go, validation/util/linux_resources_memory.go, validation/util/linux_resources_network.go, validation/util/linux_resources_pids.go, validation/util/test.go
The test harness requires TAP output.  Before this pull request:
```console
./validation/linux_cgroups_pids.t ..................... 0/1
Skipped: 1
./validation/linux_cgroups_pids.t no tests found
total ................................................. 0/1
0 passing (191.66ms)
1 pending
```
After this pull request:
```console
./validation/linux_cgroups_pids.t ..................... 3/3
total ................................................. 3/3
3 passing (185.118ms)
ok
```
This pull request also:
* DRYs up some relative/absolute tests by factoring out the shared code into `util.ValidateLinuxResources*` helpers.
* Adds a missing `AddLinuxResourcesNetworkPriorities` call; previously we were testing for a priority that we hadn't actually configured.
* Fixes a `start` → `create` typo in an …
=> validation/linux_cgroups_*: Generate TAP output (and outside-validation cleanup)

cmd/runtimetest/main.go, validation/linux_seccomp.go
=> runtimetest: add validateSeccomp

cmd/oci-runtime-tool/generate.go, generate/generate.go
The marshalling should not be required to be used inside of the interface.
=> Hooks should be passed in as rspec.Hook, not as a string.

validation/mounts.go
=> validation: add mount validation

Godeps/Godeps.json, Makefile, README.md, cmd/runtimetest/main.go, validation/create.go, validation/process_capabilities.go, validation/root_readonly_true.go, validation/util/container.go, validation/util/test.go, vendor/github.com/mndrix/tap-go/Makefile, vendor/github.com/mndrix/tap-go/tap.go, vendor/github.com/mndrix/tap-go/yaml_json.go, vendor/github.com/mndrix/tap-go/yaml_yaml.go
See ad47e7d5 (#439) about how node-tap handles YAML blocks vs. diagnostics.
=> *: Transition from tap Diagnostic(...) to YAML(...)

cmd/runtimetest/main.go
No semantic changes here, but the DRYer approach makes future pivots easier (e.g. #308).
=> cmd/runtimetest/main: Loop for DRYer validateCapabilities

README.md
Make `docs/`, which landed in #321, more discoverable.  Also document the `RUNTIME` option.
=> README: Link to the runtime API docs

validation/util/container.go
Address a previous TODO.  And now that we are using `--bundle`, we no longer need to set `cmd.Dir`.  The TODO mentions a lack of runc support, but runc supports `--bundle` since opencontainers/runc@3fe7d7f3 (opencontainers/runc#827).
=> validation/util/container: Use --bundle (and stop requiring BundleDir)

validation/create.go, validation/util/container.go, validation/util/test.go
Lean on the stdlib's [`ExitError`][1] instead of passing stderr around separately.  This makes it easy to keep all the parts of the error together, without having to worry about whether a particular command may have executed a runtime call.
[1]: https://golang.org/pkg/os/exec/#ExitError
=> validation/util/container: Use ExitError for stderr

validation/pidfile.go, validation/util/test.go
The runtime-spec [defines a `creating` status][1] and requires the `create` operation to [finish][1] [creating][2] the container.  Our command line API also [requires the `create` command to block until creation completes][4]:
> Callers MAY block on this command's successful exit to trigger post-create activity.
runc [does not support `creating` yet][5], and it seems to return from `create` before having quite finished (or we wouldn't have needed the code I'm removing in this pull request).  However, both of those are runc problems.  These tests are about validating spec compliance, not about working around runc's issues, so remove the crutches.
I've opened opencontainers/runc#1703 and opencontainers/runc#1704 on the path to fixing both of these issues upstream in runc, but I don't think …
=> validation: Remove runc 'create' exit timing crutches

.pullapprove.yml
There has been a request to relax the number of LGTMs in the tools projects to help improve merge rate.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Relax LGTM requirement

cmd/runtimetest/main.go
6d2dbbc9 (#494) put the nil-`Process` guard in, but it was a bit too coarse.  We can still run these tests with a nil `Process`, because all we need `Process` for is deciding whether or not to include `/dev/console`.
=> cmd/runtimetest/main: Run validateDefaultDevices even with process unset

validation/create.go, validation/pidfile.go, validation/state.go, validation/util/test.go
=> add 'state' test; using WaitingForStatus in insideValidation

validation/poststart.go, validation/poststop.go, validation/prestart.go
I am going to add a validation of the lifecycle, the specific norms are as follows:
>The pre-start hooks MUST be called after the start operation is called but before the user-specified program command is executed.
But I can not confirm the specific call state, so for the moment I'm just verifying that the relevant command has not been called.
This is just a preliminary idea. Lifecycle validation also need more work, any comments welcome. Or you can write a new patch.
=> add lifecycle validation

generate/generate.go
=> don't overwrite hook which has a same path

completions/bash/oci-runtime-tool, man/oci-runtime-tool-generate.1.md
This is a supplement to the #543.
=> Modify the legal value of the rootfs-propagation

validate/validate.go, validate/validate_test.go
Because there are so many cases, I only chose part of the test.
=> validate_test: add TestCheckMandatoryFields

validation/pidfile.go, validation/poststart.go, validation/poststart_fail.go, validation/poststop.go, validation/poststop_fail.go, validation/prestart.go, validation/prestart_fail.go, validation/state.go, validation/util/test.go
=> add tests when prestart/poststart/poststop hooks fail

validation/hooks.go
=> validation: implement PosixHooksCalledInOrder test

specerror/runtime.go, validation/start.go, validation/util/test.go
=> implement start operation tests

validate/validate.go, validate/validate_test.go
According to the following [specifications:](https://github.com/opencontainers/runtime-spec/blame/master/config-linux.md#L338)
``
You MUST specify at least one of weight or leafWeight in a given entry, and MAY specify both.
``
implement BlkIOWeightOrLeafWeightExist.
=> validate: add weightDevice validation

validation/kill.go, validation/killsig.go, validation/util/container.go, validation/util/test.go
=> implement kill tests

validate/validate.go, validate/validate_linux.go, validate/validate_unsupported.go
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> validate: allow non-linux compatibility

generate/seccomp/seccomp_default.go, generate/seccomp/seccomp_default_linux.go, generate/seccomp/seccomp_default_unsupported.go
This default seccomp profile may need to be used/generated from
non-linux platforms, though the use of syscall package confines the
compile to linux only
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> generate/seccomp: platform independent values

validation/util/linux_resources_blkio.go
Symptoms:
```
$ sudo validation/linux_cgroups_relative_blkio.t
not ok 6 - blkio leafWeight for 8:0 is set correctly
```
After the patch:
```
ok 6 - blkio leafWeight for 8:0 is set correctly
```
=> Fix condition in BlockIO test

cmd/runtimetest/main.go
The fields of /proc/$pid/uid_map and /proc/$pid/gid_map were parsed in
the wrong order.
Related: https://github.com/opencontainers/runtime-spec/pull/956
=> runtimetest: fix uid_map parsing

cmd/oci-runtime-tool/validate.go, validate/validate.go, validate/validate_test.go, validation/misc_props.go
test cases for AnnotationsKeyReversedDomain, AnnotationsKeyReservedNS,
AnnotationsKeyIgnoreUnknown, ExtensibilityIgnoreUnknownProp and
ValidValues
=> add annotation and prop tests

validation/util/container.go
The OCI Runtime Command Line Interface [1][1] specifies the order of the
arguments:
```
$ funC [global-options] <COMMAND> [command-specific-options] <command-specific-arguments>
```
runc [2][2] is flexible whether command-specific-options is before or
after command-specific-arguments. But crun [3][3] is not, making the
tests fail. Since the CLI spec only specifies one order, the validation
tests should respect that order.
[1]: https://github.com/opencontainers/runtime-tools/blob/master/docs/command-line-interface.md#global-usage
[2]: https://github.com/opencontainers/runc
[3]: https://github.com/giuseppe/crun
-----
/cc @giuseppe
=> validation: run CLI with correct argument order

validate/validate_linux.go
=> Validate_linux: Modify the returned error

validate/validate.go, validate/validate_linux.go
=> validate: mv deviceValid to validate_linux

validation/start.go
=> validation: Implement ProcArgsApplyUntilStart

contrib/rootfs-builder/Makefile
The previous
$(< rootfs-files)
is a Bashism that's not part of [POSIX command substitution][1].  For Bash, the `$(< …)` form is slightly faster (no need to exec `cat`), but not everyone uses Bash.
@liangchenye, I bet this is what was [happening to you][2].
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03
[2]: https://github.com/opencontainers/runtime-tools/pull/598#issuecomment-372991838
=> contrib/rootfs-builder: Use $(cat rootfs-files)

validation/linux_cgroups_cpus.go, validation/linux_cgroups_hugetlb.go, validation/util/linux_resources_blkio.go, validation/util/linux_resources_network.go
Symptoms:
```
ok 3 - blkio weight is set correctly
```
After the patch:
```
ok 3 - blkio weight is set correctly
```
I found those issues by patching runc to introduce "off-by-one" bugs and
checking if they are correctly caught by the validation tests:
https://github.com/kinvolk/runc/commits/alban/off-by-one-bugs
=> Fix error messages in validation cgroup tests

cmd/runtimetest/main.go
Don't create a new tap.T in the middle of a test but reuse the existing
one instead.
Symptoms:
```
$ sudo validation/linux_readonly_paths.t
TAP version 13
ok 1 - root filesystem
ok 2 - hostname
ok 3 - process
ok 4 - mounts
ok 5 - user
ok 6 - rlimits
ok 7 - capabilities
ok 8 - default symlinks
ok 9 - default file system
ok 10 - default devices
ok 11 - linux devices
ok 12 - linux process
ok 13 - masked paths
ok 14 - oom score adj
ok 1 # SKIP syscall action SCMP_ACT_ALLOW
ok 2 # SKIP syscall action SCMP_ACT_ALLOW
ok 3 # SKIP syscall action SCMP_ACT_ALLOW
ok 4 # SKIP syscall action SCMP_ACT_ALLOW
ok 5 # SKIP syscall action SCMP_ACT_ALLOW
ok 6 # SKIP syscall action SCMP_ACT_ALLOW
ok 15 - seccomp
ok 16 - read only paths
ok 17 - rootfs propagation
ok 18 - sysctls
ok 19 - uid mappings
ok 20 - gid …
```
=> runtimetest: count correctly TAP tests

validation/hooks_stdin.go
=> add hooks stdin test

validation/process_user.go
=> validation: add process_user validation

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md, validation/process_user.go
=> generate: add process-username option and fix it's validation

docs/command-line-interface.md, docs/runtime-compliance-testing.md
I didn't see wording in the previous version of this spec to require runtimes to support the full API, so I've added language for that here.  This ensures that callers who only need the specified API will be able to run with an any runtime that is compliant with this API.  You could get some way towards this requirement before by leaning on
[the spec's][1]:
> An implementation is compliant if it satisfies all the applicable MUST, REQUIRED, and SHALL requirements.
but there are a number of requirements that currently lack lower-level MUSTs.  For example, without the full-API requirement, the only [`delete`][2] requirement would be:
> The runtime MUST NOT attempt to read from its stdin.
You could have argued that a runtime which did not implement `delete` satisfied that condition, and so …
=> docs/command-line-interface: Require complete runtime coverage

README.md, cmd/runtimetest/main.go, error/error.go, validation/linux_masked_paths.go, validation/linux_readonly_paths.go
Granular TAP output makes it easier to see what's being tested (and what's going wrong).  You could feed this into any TAP harness you like, but I've chosen prove (it seems popular).  You need a TAP harness looking for test failures, because runtimetest now returns zero when it successfully runs the tests (regardless of whether the tests all pass).  To avoid confusing the TAP consumer, all of the non-TAP logging goes to stderr (and not stdout).
With this change, the verbose output looks like:
./test_runtime.sh ..
TAP version 13
ok 1 # SKIP root.readonly falsy
ok 2 - hostname matches expected value
ok 3 - mount "/proc" found
ok 4 - mount "/dev" found
ok 5 - mount "/dev/pts" found
ok 6 - mount "/dev/shm" found
ok 7 - mount "/dev/mqueue" found
ok 8 - mount "/sys" found
ok 9 - expected …
=> runtimetest: Make TAP output more granular

docs/devel_guidelines.md
It's not obvious how the TAP output is displayed and the meaning of the
exit value.
This documentation is meant to be for developers who want to add a new
validation test.
=> doc: add developer guidelines

validation/config_updates_without_affect.go
=> validation: Implement ConfigUpdatesWithoutAffect

.travis.yml
As golint repo does not return metadata for `go get` to work correctly, every travis build fails. Let's install golint without using go get until it's fixed.
See also https://github.com/golang/lint/issues/397
=> travis: fix fetch issue of golint

generate/generate.go, validation/linux_ns_itype.go, validation/linux_ns_nopath.go, validation/util/linux_namespace.go
This PR is to check for tests `NSNewNSWithoutPath` as well as `NSInheritWithoutType`.
* `NSNewNSWithoutPath`: "If path is not specified, the runtime MUST create a new container namespace of the given type."
* `NSInheritWithoutType`: "If a namespace type is not specified in the namespaces array, the container MUST inherit the runtime namespace of that type."
See also https://github.com/opencontainers/runtime-tools/issues/572
/cc @alban
=> validation: add tests for NSNewNSWithoutPath & NSInheritWithoutType

validation/create.go
If the runtime fails to give us the state, don't just ignore this and
skip the test but ensure we print "not ok" in the TAP output.
=> validation: create: don't skip errors on state

cgroups/cgroups_v1.go
Instead of specifying the value, use the passed in parameter. (although they have the same value)
=> cgroups_v1: Correction parameters

cgroups/cgroups_v1.go
Implement the following specerror:
CgroupsAbsPathRelToMount: In the case of an absolute path (starting with `/`), the runtime MUST take the path to be relative to the cgroups mount point.
CgroupsPathAttach: If the value is specified, the runtime MUST consistently attach to the same place in the cgroups hierarchy given the same value of `cgroupsPath`.
=> Add cgroupsPath validation

validation/kill.go, validation/kill_no_effect.go
=> add test case for KillNonCreateRunHaveNoEffect

validation/hooks_stdin.go
=> check the status of the state passed to hooks over stdin

cgroups/cgroups_v1.go, validation/linux_cgroups_devices.go, validation/linux_cgroups_relative_devices.go, validation/util/linux_resources_devices.go
On the one hand in order to achieve devices validation, on the other hand in order to achieve the following `specerror`：
`DevicesApplyInOrder`: The runtime MUST apply entries in the listed order.
But the test results are not the same as I expected, so I want to see what do you think.
```
➜  runtime-tools git:(devices-validation) ✗ sudo ./validation/linux_cgroups_devices.t
TAP version 13
ok 1 - find devices
ok 2 - get devices data
not ok 3 - devices c 10:229 rwm is set correctly
not ok 4 - devices a 10:200 r is set correctly
1..4
```
@wking @liangchenye @alban @dongsupark PTAL
=> validation: add cgroup devices validation

validation/linux_ns_path.go
This PR validates `NSProcInPath`, i.e. `The runtime MUST place the container process in the namespace associated with that path`. It checks that Linux namespaces are created with a given path by making use of `util.RuntimeOutsideValidate()`. 
Since the [previous version of PR](https://github.com/opencontainers/runtime-tools/pull/613), we had to fix the following things:
* Fix a bug caused by namespace string mismatches, found by @alban.
* Kill the unshare process as well as child processes at once, making use of `setpgid()`.
* Use a ticker loop instead of a pure sleep call for general sync mechanism.
* Print out correct diagnostics based on specError.
This PR replaces https://github.com/opencontainers/runtime-tools/pull/613.
See also …
=> validation: add test for NSProcInPath

validation/linux_ns_path.go, validation/linux_ns_path_type.go
`checkNSPathMatchType` checks if the container returns an error when deliberately setting a wrong namespace type. Doing that, it is possible to verify `NSPathMatchTypeError`, i.e. `The runtime MUST generate an error if path is not associated with a namespace of type "type"`.
See also https://github.com/opencontainers/runtime-tools/issues/572
/cc @alban 
=> validation: add a new test for NSPathMatchTypeError

README.md
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>
=> README: fix broken links to documentation

validation/hooks_stdin.go
As `stdinStateCheck()` can return nil for errs, we need to access to `errs.Error()` only when errs is not nil. So conditionally compose newError for both cases, errs == nil and errs != nil, to avoid panics like that:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f5a02]
goroutine 1 [running]:
github.com/opencontainers/runtime-tools/vendor/github.com/hashicorp/go-multierror.(*Error).Error(0x0, 0x7dfc20, 0xc420224480)
.../github.com/opencontainers/runtime-tools/vendor/github.com/hashicorp/go-multierror/multierror.go:15 +0x22
main.main()
.../github.com/opencontainers/runtime-tools/validation/hooks_stdin.go:154 +0x11ba
```
=> validation: fix nil dereference when handling multierror in hooks_stdin

cmd/runtimetest/main.go, validation/killsig.go
Inside a container, we need to check if `/dev/ptmx` exists, a symlink to `/dev/pts/ptmx`, as mentioned in the [runtime-spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#default-devices).
Also in `validation/killsig.t`, Test not only SIGTERM, but also SIGUSR1 as well as SIGUSR2.
=> validation: add minor checks for ptmx and kill signal

cmd/runtimetest/main.go, validation/linux_masked_paths.go, validation/linux_readonly_paths.go
So far tests linux_masked_paths.t & linux_readonly_paths.t have failed with error messages like `cannot test read access for "/dirname"`. That's because `testReadAccess()` only checked if the given path is a regular file, returning an error for every other case. `testReadAccess()` should actually take care of another case of a given
path being a directory, to be able to correctly check for its readability.
Also run `testFileReadAccess()` or `testFileWriteAccess()` for all file types, not only a normal file, because the runtime spec does not mandate the type of masked files. It could be actually any file, including a character device like `/dev/null`, especially in case of runc.
Found by @alban.
=> runtimetest: correctly check for a readable directory

generate/config.go, generate/generate.go, validation/linux_cgroups_blkio.go, validation/linux_cgroups_cpus.go, validation/linux_cgroups_devices.go, validation/linux_cgroups_hugetlb.go, validation/linux_cgroups_memory.go, validation/linux_cgroups_network.go, validation/linux_cgroups_pids.go, validation/linux_cgroups_relative_blkio.go, validation/linux_cgroups_relative_cpus.go, validation/linux_cgroups_relative_devices.go, validation/linux_cgroups_relative_hugetlb.go, validation/linux_cgroups_relative_memory.go, validation/linux_cgroups_relative_network.go, validation/linux_cgroups_relative_pids.go, validation/linux_ns_itype.go, validation/linux_ns_nopath.go, validation/linux_ns_path.go, validation/linux_ns_path_type.go, validation/util/linux_resources_blkio.go, validation/util/linux_resources_cpus.go, validation/util/linux_resources_devices.go, validation/util/linux_resources_memory.go, validation/util/linux_resources_network.go, validation/util/linux_resources_pids.go, validation/util/test.go
This PR tries to cover more test cases by running cgroup tests with different combinations of input values. Also it tries to print out detailed output results in the TAP format.
To do that, first of all, we change prototype of `RuntimeOutsideValidate()` as well as `AfterFunc()`, updating all corresponding call sites. And then we update cgroups tests. Changed cgroups tests are:
* Memory 
* CPU
* Network
* Blkio
* HugeTLB
Especially I needed to update CPU cgroups tests a lot, by following the same semantics of memory cgroups. For that, I had to add helpers in `validation/util/linux_resources_cpus.go`.
/cc @alban
=> validation: test cgroups with different input values

validation/linux_masked_paths.go
Split out the test function into `checkMaskedPaths()`, and add more cases for masked paths like subdirectory, file under subdirectory, and directory under subdirectory.
Test inside container should return error if a relative path is given for masked paths.
Deliberately create an invalid symlink that points out of the container, to see if the test fails inside the container.
Create masked block device, char device, and fifo, to check if they are masked as expected.
=> validation: add more test cases for masked paths tests

validation/linux_readonly_paths.go
Split out the test function into `checkReadonlyPaths()`, and add more cases for read-only paths like subdirectory, file under subdirectory, and directory under subdirectory.
Test inside container should return error if a relative path is given for read-only paths.
Deliberately create an invalid read-only symlink that points out of the container, to see if the test fails inside the container.
Create read-only block device, char device, and fifo, to check if they are read-only as expected.
=> validation: add more test cases for read-only paths tests

validation/config_updates_without_affect/config_updates_without_affect.go, validation/delete/delete.go, validation/hooks_stdin/hooks_stdin.go, validation/hostname/hostname.go, validation/kill_no_effect/kill_no_effect.go, validation/killsig/killsig.go, validation/linux_ns_itype/linux_ns_itype.go, validation/linux_ns_nopath/linux_ns_nopath.go, validation/start/start.go
So far `util.Fatal()`, which calls `os.Exit(1)`, has been widely used to exit immediately when a critical error happened. Its downside is though that no further function can be called after that moment, even defer functions cannot be called. That's fine if there's nothing to clean up or the test is simple enough. Though it could be an issue, for example, when a test should print out TAP output by calling `t.AutoPlan()`, or when it should clean up something.
So let's try to use `util.Fatal()` only for errors from critical cases like errors from `util.GetDefaultGenerator()` or `util.PrepareBundle()`. In case of main test errors, use instead `t.Fail(err.Error())` to print out errors in TAP outputs.
Partly addresses https://github.com/opencontainers/runtime-tools/issues/582
/cc @liangchenye …
=> validation: use t.Fail when checking for main test errors

cgroups/cgroups.go, cmd/runtimetest/mount/mountinfo_linux.go
The source of a mount in /proc/self/mountinfo can unfortunately be an
empty string. Before this patch, 'mount' and 'mountpoint' fail as
following:
```
$ sudo mount -t tmpfs "" /tmp/bb
$ mount
mount: /proc/self/mountinfo: parse error at line 64 -- ignored
$ mountpoint /tmp/bb
/tmp/bb is not a mountpoint
```
This patch fixes the parsing.
-----
Similar patch in util-linux: https://www.spinics.net/lists/linux-fsdevel/msg128896.html
Similar PR in runc: https://github.com/opencontainers/runc/pull/1829
Related patch that would fix this kernel-side: https://patchwork.kernel.org/patch/10349095/
=> mountinfo: parse empty strings in source

cmd/runtimetest/main.go, validation/mounts/mounts.go
The runtime-spec says that [mount source is optional](https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config.md#mounts). So let's relax condition of the mount source path check, so that it only checks for an empty mount source. Ditto for the type field.
The 'mount' test now tries different mount options: bind and not bind, recursive or not, different mount propagation modes.
runc passes the test after https://github.com/opencontainers/runc/pull/1845
Closes: https://github.com/opencontainers/runtime-tools/issues/651
Based on work from: Dongsu Park <dongsu@kinvolk.io> @dongsupark 
=> validation: mounts: fix condition of source & type check

generate/generate.go
=> /proc should be mounted with nosuid, noexec, nodev to match the host

validation/delete_only_create_resources/delete_only_create_resources.go, validation/delete_resources/delete_resources.go
```
DeleteResImplement: Deleting a container MUST delete the resources that were created during the create step.
DeleteOnlyCreatedRes: Note that resources associated with the container, but not created by this container, MUST NOT be deleted.
```
At present, `DeleteResImplement` is implemented, but it is not yet clear how to implement `DeleteOnlyCreatedRes`. (Write the container id to the existing `cgroup tasks`?)
@liangchenye @dongsupark @wking WDYT?
=> add resource validation after delete

README.md
Signed-off-by: Ace-Tang <aceapril@126.com>
fix `validation/default.t` path wrong in readme.
=> readme: fix wrong filepath

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/config.go, generate/generate.go, man/oci-runtime-tool-generate.1.md
Initialize the windows network config during Network Namespace initialization
Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>
=> Initialize Config Windows Network for Windows Namespace

cmd/oci-runtime-tool/generate.go, man/oci-runtime-tool-generate.1.md
After modification, you can add or delete multiple capabilities with one command.
```
oci-runtime-tool generate  --process-cap-add-ambient CAP_FOWNER,CAP_FSETID
```
Fixes #673 
=>  generate: fix capabilities add/drop option

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Add process-cap-add option to add Linux capabilities to all 5 capability sets.
```
oci-runtime-tool generate --process-cap-add CAP_FOWNER,CAP_FSETID
```
Add process-cap-drop option to drop Linux capabilities to all 5 capability sets.
```
oci-runtime-tool generate --process-cap-drop CAP_FOWNER,CAP_FSETID
```
=> generate: add process-cap-add and process-cap-drop option

Godeps/Godeps.json, validate/validate_test.go, vendor/github.com/hashicorp/go-multierror/.travis.yml, vendor/github.com/hashicorp/go-multierror/format.go, vendor/github.com/hashicorp/go-multierror/go.mod, vendor/github.com/hashicorp/go-multierror/go.sum, vendor/github.com/hashicorp/go-multierror/multierror.go, vendor/github.com/hashicorp/go-multierror/sort.go
=> Godeps: update hashicorp/go-multierror

Godeps/Godeps.json, cmd/runtimetest/main.go, validate/validate.go, validate/validate_linux.go, validation/linux_mount_label/linux_mount_label.go, vendor/github.com/opencontainers/selinux/LICENSE, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
1. update godeps and add go-selinux deps
2. add selinux check in validate and runtimetest
Close #386 
This is a rebase of #386 
=> Add SELinux Check

README.md
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
This will add a link to the code of conduct and security pages to address https://github.com/opencontainers/org/issues/3
=> adding security and CoC links

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Add oci-version option to generate to set the version of the Open Container Initiative runtime specification.
=> generate: add oci-version option

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, man/oci-runtime-tool-generate.1.md
Signed-off-by: John Howard <jhoward@microsoft.com>
There were a few typos `Winodws` which should be `Windows` (obviously).
It also corrects the defaults for Windows. Neither `IgnoreFlushesDuringBoot` nor networkings `AllowUnqualifiedDNSQuery` should be defaulted to true. Also, the assumption that there is a console is incorrect. These should all be set explicitly, if required, by callers.
@jterry75 FYI
=> Windows: Typos and incorrect defaults

Makefile, cmd/runtimetest/main.go, validation/delete/delete.go, validation/kill/kill.go, validation/linux_seccomp/linux_seccomp.go, validation/misc_props/misc_props.go, validation/pidfile/pidfile.go, validation/process_capabilities_fail/process_capabilities_fail.go, validation/state/state.go, validation/util/container.go, validation/util/test.go
this PR includes several minor fixes to the validation tests.  I've found these issues while preparing `crun` to be fully OCI compliant: https://github.com/giuseppe/crun/pull/16
More details are included in the commit message for each patch.
I've added a patch for the Makefile to print what validation-tests are used.  I want to use it on Travis to easily read the list of the tests and disabling some of them, namely some cgroup tests that require a special configuration (I could just repeat the same find query, but I'd prefer to keep this logic in the runtime-tools Makefile)
=> validation-tests: fix several tests

generate/generate.go, generate/generate_test.go
AddProcessEnv was sequentially going through the env array
to check for duplicates, which would become very slow if we
add a huge amount of ENV vars.
Add a map to Generator to keep track of the ENV vars already
added, so that when AddProcessEnv checks for duplicates, it is
much faster.
Also add a new function called AddMultipleProcessEnv,
which takes a []string of ENVs and adds them to the config in one
go.
Add unit tests for these functions.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
=> Improve performance of AddProcessEnv

cgroups/cgroups_v1.go, validation/linux_cgroups_hugetlb/linux_cgroups_hugetlb.go, validation/linux_cgroups_relative_hugetlb/linux_cgroups_relative_hugetlb.go
This is ~a cherry-pick of https://github.com/opencontainers/runc/pull/2065.
The hugetlb cgroup control files (introduced here in 2012:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=abb8206cb0773)
use "KB" and not "kB"
(https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/hugetlb_cgroup.c\?h\=v5.0\#n349\).
The behavior in the kernel has not changed since the introduction, and
the current code using "kB" will therefore fail on devices with small
amounts of ram (see
kubernetes/kubernetes#77169) running a kernel
with config flag CONFIG_HUGETLBFS=y
As seen from the code in "mem_fmt" inside hugetlb_cgroup.c, only "KB",
"MB" and "GB" are used, so the others may be removed as well.
Here is a real world example of the files inside the …
=>  Fix cgroup hugetlb size prefix for kB 

generate/generate.go
The existing diagnostic[1] appeared in a CI job with no
possible hope of figuring out the source of the problem.
This PR amends the diagnostic to include the name of
the requested newly-created device as well as the
existing "duplicate".
[1] WARNING: The same type, major and minor should not be used for multiple devices.
(I am not convinced that this condition merits a warning
but will leave that discussion to better minds than mine).
Signed-off-by: Ed Santiago <santiago@redhat.com>
=> AddDevice(): better diagnostic when creating dup

generate/seccomp/seccomp_default.go
Fixes https://github.com/opencontainers/runtime-tools/issues/699
This PR adds the missing [clone masked_eq seccomp](https://github.com/cri-o/cri-o/blob/master/vendor/github.com/seccomp/containers-golang/seccomp.json#L607-L632) rule which causes clone syscalls to fail on s390x.
I have only tested this patch directly in cri-o so far.  Please consider this PR a work in progress while I become familiar with this project and its processes such as writing and running unit tests, etc.
Additionally, since this patch only affects s390x, please let me know if there is anything extra I should do to test the architecture-specific functionality.
Thanks,
DB
=> Add missing clone rule for s390x. Fixes #699

generate/generate.go
If a user wants to add multiple devices under different paths,
why should the runtime-tools complain?  This seems like a useles
warning.
=> Remove spurious WARNING message

Godeps/Godeps.json, generate/generate.go, validate/validate.go, validate/validate_test.go, validation/util/test.go, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/state.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
umask is a pointer to an uint32.
The error was first present in the runtime-specs Go bindings and it
was fixed with:
https://github.com/opencontainers/runtime-spec/pull/1058
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> generate: fix type for Umask

validation/hooks_stdin/hooks_stdin.go
do not read the container pid in PreDelete as it might be already
terminated ("true" is a short lived process).
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> validation: read pid in PostCreate

validation/linux_cgroups_hugetlb/linux_cgroups_hugetlb.go, validation/linux_cgroups_relative_hugetlb/linux_cgroups_relative_hugetlb.go
Use explicit 64-bit types to avoid fall-back on incompatible 32-bit
types on 32-bit platforms.
Fixes: #711
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
=> Fix build of hugetlb tests on 32-bit platforms

validation/util/container.go, validation/util/test.go
This reverts commit 0ab61aed92a67a6e72b68fc0dd6322c95e4bb05b, and also
* changes `ReadStandardStreams` to use `ioutils.ReadFile`;
* changes the uuid module used by the code (see commit abcb94dc55c6c4a).
Using `bytes.Buffer` instead of plain `os.File` results in go runtime
creating two sets of pipes and spawning two threads (for stdout and
stderr) that copy the data from the pipe to the buffers.
It is not working when we execute runc create, because it spawns a child
(runc init) whose stdout and stderr are kept connected to the write ends
of the above pipes. As a result, those copying routines never finish,
and `cmd.Run()` never returns as it waits for those routines.
Therefore, let's go back to using temporary files. Note that the new
code is using `ioutil.ReadAll` instead of reusing the …
=> Fix hanging on runc create.

generate/config.go, generate/generate.go
From
- [#1040](https://github.com/opencontainers/runtime-spec/pull/1040).
- [#KEP-2570: Support memory qos with cgroups v2](https://github.com/kubernetes/enhancements/pull/2571)
- [#102578](https://github.com/kubernetes/kubernetes/pull/102578).
When use cgroup v2, containerd and cri-o should set unified. 
Signed-off-by: Zhiyu Li <payall4u@qq.com>
=> spec generator support setting unified

cmd/runtimetest/main.go, validation/create/create.go, validation/linux_rootfs_propagation/linux_rootfs_propagation.go, validation/util/container.go, validation/util/test.go
This is another follow up to PRs #728 and #732, fixing a few issues introduced by them, with some related cleanups and fixes. Please see individual commits for more details.
In particular, this fixes rootfsPropagation test failure when running the test inside a Docker container), caused by https://github.com/opencontainers/runtime-tools/pull/732/commits/8e1a3b587864ef065f7eff09e54933720d950117 (which adds new capabilities to the list, and those caps are not yet known to Docker daemon used for CI).
Currently a draft which I am about to test in crun repo.
=> Followup fixes to validator

generate/seccomp/seccomp_default.go
syscall "statx" was first introduced by kernel at version 4.11, which
is a new implementation of stat, caller can request specific
information(file size only) to speed up the call. Docker has the statx
in seccomp config as well.
Signed-off-by: CooperLi <1866858@gmail.com>
=> Add syscall "statx" in seccomp to fix Operation not permitted

Makefile, README.md
Apparently, TAP is used by node-tap, so when it is used to specify a
path to node-tap, this results in a failure:
$ make TAP=/path/to/node-tap localvalidation
...
Error: Environment variable TAP must be set to 0 or 1 only
Fixes: #723
=> Makefile: replace TAP with TAPTOOL

.github/workflows/test.yml
The job `lint` has a lot of errors from typecheck that don't seem valid. The new golangci-lint with the new Go doesn't complain about the existing code.
=> Use new golangci-lint

cmd/oci-runtime-tool/generate.go, completions/bash/oci-runtime-tool, generate/generate.go, go.mod, go.sum, man/oci-runtime-tool-generate.1.md, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/state.go, vendor/modules.txt
runtime-spec recently added support for a Domainname entity, add handling for it here to be used by runtimes.
Signed-off-by: Charlie Doern <cdoern@redhat.com>
=> generate: add support for domainname

validate/validate.go, validate/validate_test.go
This is a carry of #688, using a slightly different fix. In addition, it adds a test case, and fixes the error texts.
Closes: https://github.com/opencontainers/runtime-tools/pull/688
=> validate: fix panic

generate/seccomp/seccomp_default.go, generate/seccomp/seccomp_default_linux.go
All clone flags should be denied as default profile.
Also x/sys should be used instead of syscall.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
=> seccomp: add CloneNewCgroup to check sysCloneFlagsIndex

generate/generate.go
The recommended replacement does not work because other code paths expect
an initialized envCacheMap.
Fixes #720
=> generate: NewFromSpec() remove deprecated comment

generate/generate.go, validate/capabilities/validate.go, validate/capabilities/validate_linux.go, validate/capabilities/validate_unsupported.go, validate/validate.go, validate/validate_linux.go
Split out those few capability validation functions (`LastCap()`, `CapValid()`) which `Generator` depends on into a `validate/capabilities` subpackage of their own. This should prevent `github.com/xeipuuv/gojson*` from sneaking in to the dependencies of anyone who uses `Generator` for `OCI Spec` manipulation.
Those `gojsonschema` and related packages are often considered problematic because they do not seem to be actively maintained. At the time of this commit they received their last updates in 2018, 2019 and 2020. Excluding them from the dependency blast radius can lower the barrier for accepting/allowing import of generate.Generator.
=> generate, validate: isolate gojson* dependencies.

generate/seccomp/seccomp_default.go
Separate each syscall condition (argument) for personality syscall into
a single rule because the libseccomp can only compare each condition once
in a single rule. Otherwise, the adding returns EINVAL on failure.
In order to address the failure, general OCI runtimes such as runc add each
condition as a separate rule if two or more conditions have the same conditions,
but this is a way for keeping compatibility (old behavior). Hence, it will lead
wrong behavior because the conditions for the rules will be logical-OR instead of
logical-AND.
In case of the OCI tests for personality syscall, we should explicitly separate
the conditions into a single rule as logical-OR for container runtimes that do not
support the above old behavior.
Ref. …
=> seccomp: Separate conditions for personality syscall into single rule

generate/generate.go
Closes: #759 
This reverts commit 09d837bf40a7356a478e40642e36f5f7e1dea7d1.
Mounting /dev with 'noexec' option triggers problems when containers try to create Intel SGX enclaves:
...
ioctl(4, SGX_IOC_ENCLAVE_ADD_PAGES, 0x7ffd38e7bf90) = 0 mmap(0x7f36d9002000, 139264, PROT_READ|PROT_EXEC, MAP_SHARED|MAP_FIXED, 4, 0) = -1 EPERM (Operation not permitted) close(4)
...
The issue where a device node is mmap()'d with PROT_EXEC has been discussed in length on Linux development mailing lists and with udev/systemd maintainers [1].
As a result of this conversation, systemd changed its defaults to mount /dev with 'exec' [2] and added ExecPaths= and NoExecPaths= [3] to let users to control the behavior.
Change runtime-tools to follow the systemd default and to get the runtime behavior fixed for Intel …
=> Revert "Change /dev to be mounted by default with /noexec"

cgroups/cgroups.go, cgroups/cgroups_v1.go, cmd/runtimetest/main.go, generate/generate_test.go, validate/validate.go, validate/validate_test.go, validation/delete_only_create_resources/delete_only_create_resources.go, validation/hooks/hooks.go, validation/hooks_stdin/hooks_stdin.go, validation/linux_masked_paths/linux_masked_paths.go, validation/linux_readonly_paths/linux_readonly_paths.go, validation/misc_props/misc_props.go, validation/pidfile/pidfile.go, validation/poststart/poststart.go, validation/poststart_fail/poststart_fail.go, validation/poststop/poststop.go, validation/poststop_fail/poststop_fail.go, validation/prestart/prestart.go, validation/start/start.go, validation/util/container.go, validation/util/linux_resources_cpus.go, validation/util/test.go
Package io/ioutil has been marked deprecated in Go 1.16. Updates io/ioutil to os package alternatives.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Remove io/ioutil package references.

cgroups/cgroups.go, cmd/oci-runtime-tool/generate.go, cmd/runtimetest/main.go, generate/generate.go, generate/generate_test.go, generate/seccomp/parse_action.go, generate/seccomp/seccomp_default.go, specerror/bundle.go, specerror/runtime-linux.go, validate/validate.go, validate/validate_linux.go, validate/validate_test.go, validation/delete/delete.go, validation/delete_only_create_resources/delete_only_create_resources.go, validation/delete_resources/delete_resources.go, validation/kill/kill.go, validation/kill_no_effect/kill_no_effect.go, validation/killsig/killsig.go, validation/linux_cgroups_hugetlb/linux_cgroups_hugetlb.go, validation/linux_cgroups_relative_hugetlb/linux_cgroups_relative_hugetlb.go, validation/linux_masked_paths/linux_masked_paths.go, validation/linux_readonly_paths/linux_readonly_paths.go, validation/linux_seccomp/linux_seccomp.go, validation/misc_props/misc_props.go, validation/prestart_fail/prestart_fail.go, validation/process/process.go, validation/process_user/process_user.go, validation/state/state.go, validation/util/container.go
format the code with gofumpt (which is a superset of gofmt)
=> gof(ump)t code

go.mod, go.sum, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go, vendor/modules.txt
Update some dependencies to released versions;
full diff: https://github.com/opencontainers/runtime-spec/compare/86290f6a00fb...v1.1.0
=> update runtime-spec v1.1.0

.github/workflows/test.yml, cmd/oci-runtime-tool/main.go
Mostly a CI refresh. See commits for details.
Closes: #769
=> Add Go 1.22 and 1.23, rm old versions, bump CI actions, bump golangci-linter
