MAINTAINERS

Since this project is based on ocitools and OCT, 
I propose to add Mrunal and me as the initial maintainers. 
There are other contributers  who also makes great work on it,
I think we can add more since ocitools will become bigger :) 
Signed-off-by: liangchenye liangchenye@huawei.

Add Maintainer

---

generate.go

Add support for the no new privs flag

---

bvalidate.go

Fix format flag (reported by go vet)

---

generate.go

Add support for sysctls to generate

---

generate.go

Add support for enabling/disabling tty to generate

---

generate.go

Don't set hostname by default

---

generate.go

Only set boolean parameters if they are passed as flags

---

generate.go

Add support for annotations(labels) to generate

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/opencontainers/runtime-spec/LICENSE
Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go
Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go
generate.go

Add support for mount label to generate

---

generate.go

Add convenience flag seccomp-allow to generate

---

README.md

"OCI compatable runtime" --> "OCI compatible runtime"
Signed-off-by: Rob Dolin <RobDolin@microsoft.com>

[ ReadMe ] Spelling fix

---

completions/bash/ocitools

Fixes for bash completions

---

man/ocitools-generate.1.md
man/ocitools-validate.1.md
man/ocitools.1.md

ocitools/man: small fix

---

cmd/runtimetest/main.go

runtimetest/hostname: small fix for null hostname

---

completions/bash/ocitools

add --hooks option for validate completion

---

man/ocitools-generate.1.md
man/ocitools.1.md

tfix and --root-propagtion accept lowercase value

ocitols mans: tfix

---

generate.go
man/ocitools-generate.1.md

generate: add specified cgroups path support

---

cmd/runtimetest/main.go

reduce one loop and unnecessary map variable

runtimetest: optimize capabilities validation

---

cmd/runtimetest/main.go

Modify the display message for validating root filesystems

---

README.md
validate.go

Add default value for `--path` opt of `validate`

---

generate.go
validate.go

The signature now requires returning an error.

Update Action Function signature for validate

---

cmd/runtimetest/main.go
generate.go
main.go
test_runtime.sh
validate.go

Details in the commit messages.

Add --log-level flags to ocitools and runtimetest

---

generate.go
man/ocitools-generate.1.md

generate: Add support for --seccomp-errno

---

validate.go

validation: add cgroup namespace check

---

generate.go
main.go
validate.go

small fix: format codes

---

man/ocitools-generate.1.md

man/ocitools-generate: small fix

---

validate.go

validate: complete seccomp check

---

man/ocitools-generate.1.md

ocitools-generate.1.md change specifiy to specifies

---

cmd/runtimetest/main.go

validation: add linux default devices validation

---

cmd/runtimetest/main.go

add fatal error msg back to runtimetest

---

validate.go

Fix `dies on the first error` issue mentioned in https://github.com/opencontainers/ocitools/issues/98.
Check/validate all the tests, output all the error messages.
It works better with https://github.com/opencontainers/ocitools/pull/97.

Change Fatal to Error

---

generate.go
validate.go

tfix: usage of validate and generate

---

Makefile

Makefile: clean up compiled man page

---

generate/generate.go

Use Generator pointers as methods receivers

---

cmd/ocitools/generate.go

generate: remove unuseful default value for output

---

generate/generate.go

generate: fix tmpfs adding based on manpage

---

cmd/runtimetest/main.go

Remove unnecessary else

---

generate/generate.go

generate: remove unnecessary spec initialization

---

generate/generate.go

Signed-off-by: masm <mashimiao.fnst@cn.fujitsu.com>
Backported to v1.0.0-rc1 from f7df9c7 #157 (cherry-pick applied cleanly).

generate: fix capability.List() for cap_last_cap not exist

---

cmd/ocitools/generate.go
generate/generate.go

Backport #169 to v1.0.0.rc1 (cherry-picks apply cleanly).

[1.0.0.rc1] Modify generate API

---

generate/generate.go

generate: fix mount-cgroups bug

---

cmd/ocitools/validate.go

Backported to v1.0.0.rc1 from bf50b73b #199 (cherry-pick applied
cleanly).

[1.0.0.rc1] add namespace check for uid/gid mappings

---

cmd/oci-runtime-tool/main.go

update command name and description

---

README.md

README: update Build Status

---

README.md

Backported to v1.0.0.rc1 from e3167e3 #224 (cherry-pick applied cleanly).

[1.0.0.rc1] README: update Build Status

---

cmd/runtimetest/main.go

small fix: fomart variable as CamelCase

---

cmd/oci-runtime-tool/validate.go
cmd/runtimetest/main.go

fix: make config path as const

---

cmd/runtimetest/main.go

runtimetest: reassign Linux-based validation

---

cmd/runtimetest/main.go

runtimetest: split linux specified part of process validation

---

.pullapprove.yml

add pullapprove.yml as PullApprove enabled

---

cmd/oci-runtime-tool/generate.go

Set pids limit when set through the CLI

---

test_runtime.sh

Fix the argument for passing rootfs path to generate

---

Makefile

Makefile: add uninstall

---

cmd/oci-runtime-tool/generate.go
completions/bash/oci-runtime-tool
generate/generate.go
generate/spec.go
man/oci-runtime-tool-generate.1.md

generate: add network related option

---

MAINTAINERS_GUIDE.md

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

fix typo and remove trailing blank

---

completions/bash/oci-runtime-tool
man/oci-runtime-tool.1.md

completions: update based current implementation

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/hashicorp/errwrap/LICENSE
Godeps/_workspace/src/github.com/hashicorp/errwrap/README.md
Godeps/_workspace/src/github.com/hashicorp/errwrap/errwrap.go
Godeps/_workspace/src/github.com/hashicorp/go-multierror/.travis.yml
Godeps/_workspace/src/github.com/hashicorp/go-multierror/LICENSE
Godeps/_workspace/src/github.com/hashicorp/go-multierror/Makefile
Godeps/_workspace/src/github.com/hashicorp/go-multierror/README.md
Godeps/_workspace/src/github.com/hashicorp/go-multierror/append.go
Godeps/_workspace/src/github.com/hashicorp/go-multierror/flatten.go
Godeps/_workspace/src/github.com/hashicorp/go-multierror/format.go
Godeps/_workspace/src/github.com/hashicorp/go-multierror/multierror.go
Godeps/_workspace/src/github.com/hashicorp/go-multierror/prefix.go
cmd/runtimetest/main.go

This makes runtime validation report all errors at the end.

Report all errors

---

man/oci-runtime-tool-generate.1.md
man/oci-runtime-tool-validate.1.md

fix description file

---

cmd/runtimetest/main.go
generate/generate.go

small fix: remove unneeded break

---

man/oci-runtime-tool.1.md

oci-runtime-tool.md: fix info

---

man/oci-runtime-tool-generate.1.md

man: fix info

---

validate/validate.go

Signed-off-by: liangchenye <liangchenye@huawei.com>

fix compile error by previous pr

---

cmd/oci-runtime-tool/generate.go

cmd/generate: tfix

---

completions/bash/oci-runtime-tool

completions: cleanup and fix

---

completions/bash/oci-runtime-tool

add --uid and --gid to bash-completion.

bash-completion: add --uid and --gid and some trivial change

---

validate/validate.go

validate: add path check for namespace

---

completions/bash/oci-runtime-tool

completions: fix oom-score-adj

---

validate/validate.go

validate: add windows validation in checkos

---

validate/validate.go

validate: perfect deviceValid

---

generate/generate.go
validate/validate.go

tfix and format comment

---

cmd/oci-runtime-tool/generate.go
completions/bash/oci-runtime-tool
man/oci-runtime-tool-generate.1.md

generate: add cap-drop-all option

---

validate/validate.go

validate: modify the information output

---

validate/validate.go

https://golang.org/doc/install/source#environment

validate.go：increase the type of checkplatform

---

validate/validate.go

validate: modify rlimit validation

---

validate/validate.go

validate: modify the validation scope of mount.destination

---

man/oci-runtime-tool-generate.1.md

man: fix typo

---

cmd/runtimetest/main.go

runtimetest: add path option

---

validate/validate.go

https://github.com/opencontainers/runtime-spec/blame/master/config.md#L42

validate: increase readonly validation

---

generate/seccomp/parse_action.go

Fixes #395 
Signed-off-by: grantseltzer <grant@capsule8.com>

Fix error when seccomp action is specified the same as default

---

validation/validation_test.go

add error catch

---

cmd/runtimetest/main.go

runtimetest: void panic when capaibilities is nil

---

validate/validate.go

validate: improve cap check

---

Makefile

makefile: guarantee runtimetest exists

---

completions/bash/oci-runtime-tool

remove os,arch from completions

---

Makefile
cmd/runtimetest/main.go
validation/validation_test.go

automatically get os when validating runtime

---

validate/validate.go

https://github.com/opencontainers/runtime-spec/blame/master/config.md#L349

validate: increase the validation of windows fields

---

completions/bash/oci-runtime-tool

add completion for --platform

---

cmd/oci-runtime-tool/generate.go
completions/bash/oci-runtime-tool
generate/generate.go
man/oci-runtime-tool-generate.1.md

generate: add hugepage limit related option

---

cmd/oci-runtime-tool/generate.go
completions/bash/oci-runtime-tool
generate/generate.go
generate/spec.go
man/oci-runtime-tool-generate.1.md

add ConsoleSize option

---

validate/validate.go

Signed-off-by: zhouhao zhouhao@cn.fujitsu.com

validate: Add non-empty checks 

---

validation/validation_test.go

use default runtime to test when the runtime env is not set

---

error/runtime_spec.go

error: small fix

---

cmd/oci-runtime-tool/main.go
cmd/runtimetest/main.go

VERSION: release v0.1.0

---

completions/bash/oci-runtime-tool

fix broken cap completion

---

validate/validate.go

validate: Remove the wrong seccompAction valid value

---

generate/generate.go

fix pointed out issue at [here](https://github.com/opencontainers/runtime-tools/pull/466#issuecomment-327980693)

cap: drop existent item before validating

---

validate/validate.go

Since #197 merged, it has verified.

validate: Delete the extra validation

---

validate/validate.go

fix compile issue

---

completions/bash/oci-runtime-tool

bash: fix commands

---

specerror/config.go
specerror/runtime.go

complete RFC codes of runtime.md

---

CHANGELOG.md
cmd/oci-runtime-tool/main.go
cmd/runtimetest/main.go

release v0.3.0

---

cmd/runtimetest/main.go

runtimetest: fix error return

---

validate/validate_test.go

validate_test: add cwd check to TestCheckProcess

---

cmd/runtimetest/main.go

move validateRlimits to defaultValidations

---

cmd/oci-runtime-tool/generate.go

generate: fixed seccompSet

---

cmd/runtimetest/main.go

runtimetest: remove debug info 

---

generate/generate.go

generate: fix error return

---

validation/validation_test.go

1. add preFunc() to set test environment before container running
2. add all left behind tests for container inside validation

Complete Container Inside Test

---

validate/validate.go

validate: fix nil deference

---

man/oci-runtime-tool-generate.1.md

man: small fixs

---

validate/validate_test.go

validate_test: add TestCheckLinux

---

cmd/oci-runtime-tool/generate.go
generate/generate.go

Delete some unnecessary return value.

generate: modify the function return value

---

cmd/oci-runtime-tool/generate.go
completions/bash/oci-runtime-tool
generate/generate.go
generate/spec.go
man/oci-runtime-tool-generate.1.md

Add some options to generate windows-specific container configuration.

generate: windows-specific container configuration generate

---

validate/validate_test.go

The test for the `DefaultAction` will be added after the spec is improved.

validate_test: perfect TestJSONSchema

---

MAINTAINERS_GUIDE.md

change two LGTMs requirement to one

---

validation/poststart.go
validation/poststop.go
validation/prestart.go
validation/util/container.go
validation/util/test.go

nil config support in lifecycle validate

---

validate/validate_test.go

validate_test: Complement test

---

validate/validate.go

validate: implement DevicesErrorOnDup

---

validation/state.go
validation/util/container.go

implement DefaultStateJSONPattern test

---

validate/validate.go

validate: add logrus.Debugf to CheckJSONSchema

---

validation/poststart.go
validation/poststop.go
validation/prestart.go

validation: Increase err judgment

---

generate/generate.go

@mrunalp PTAL (related to https://github.com/kubernetes-incubator/cri-o/issues/1312)
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

generate: fix handling of permitted caps drop

---

validation/hooks.go
validation/poststart.go
validation/poststop.go
validation/prestart.go
validation/start.go

validation: Add error judgment to SetConfig

---

cmd/runtimetest/main.go

Implement PosixProcRlimitsSoftMatchCur and PosixProcRlimitsHardMatchMax

---

validation/process_capabilities_fail.go
validation/process_rlimits_fail.go

Implement PosixProcRlimitsTypeGenError and LinuxProcCapError

---

validation/process_rlimits.go

validation: Add system validation

---

validation/process_rlimits_fail.go

Add system validation

---

validation/test-yaml

I'd accidentally committed it in 3bd8d43 (#542).

validation/test-yaml: Drop this local experiment

---

generate/generate_test.go

fix generate test in calling generate.New

---

README.md
cmd/runtimetest/main.go
man/oci-runtime-tool-generate.1.md
validation/util/container.go

fix some misspells

---

Godeps/Godeps.json
generate/generate.go
man/oci-runtime-tool-generate.1.md
validate/validate_test.go
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>

Vendor in windows runtime-spec changes

---

Makefile

test the test files under the generate folder.

Makefile: add generate to gotest

---

generate/generate.go
generate/generate_test.go
validate/validate_test.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

Adds default generate support for Windows specs.
Fixes the generate/validate tests on Windows.
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

Add generate.New support for Windows.

---

.travis.yml
README.md

update to golang 1.11

---

validate/validate_test.go
validation/mounts/mounts.go

Simplified code

---

cmd/runtimetest/main.go
validation/linux_process_apparmor_profile/linux_process_apparmor_profile.go

Add apparmorProfile validation in runtimetest and validation.

Add apparmor profile test

---

generate/generate.go

Signed-off-by: Doug Rabson <dfr@rabson.org>

Add generator support for FreeBSD
